### ISSUE TITLE
[docker] [alpine linux] running tests issue

### ISSUE THREAD

**Issue by albundy83** [edenhill/librdkafka#1046]
Description
===========

Hello,
I'm trying to run the tests to validate the build for alpine linux 3.4 in docker.
But I can't make it work.

How to reproduce
================
Using the following Dockerfile : 
```docker
FROM alpine:3.4

WORKDIR /src

RUN apk update \
    && apk add bash \
    && apk add --no-cache --virtual .build-deps ca-certificates make gcc g++ python zlib-dev openssl-dev cyrus-sasl-dev lz4-dev libc-dev bsd-compat-headers py-setuptools

ADD https://github.com/edenhill/librdkafka/archive/master.zip /src/librdkafka.zip

RUN unzip librdkafka.zip \
    && cd /src/librdkafka-master \
    && ./configure \
    && make \
    && make install

ADD https://github.com/edenhill/trivup/archive/master.zip /src/trivup.zip

RUN unzip trivup.zip \
    && cd /src/trivup-master \
    && python setup.py install

COPY test.conf /src/librdkafka-master/tests/

RUN cd /src/librdkafka-master/tests \
    && ./broker_version_tests.py --debug
```
The file test.conf contains : 
```bash
# Bootstrap broker(s)
metadata.broker.list=localhost:9092
# Debugging
debug=metadata,topic,msg,broker
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):https://github.com/edenhill/librdkafka/commit/dde5ecf0a02db2f938312812cae52c234d560c1b
 - [x] Apache Kafka version: 2.11-0.10.1.0
 - [x] librdkafka client configuration: NA
 - [x] Operating system: Alpine Linux 3.4 in docker
 - [x] Using the legacy Consumer: no
 - [x] Using the high-level KafkaConsumer: no
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: yes
 - [x] Provide broker log excerpts: NA
 - [x] Critical issue: no

```bash
./broker_version_tests.py --debug
 ---> Running in 25e1253029eb
#### Version 0.8.1.1, suite standard: STARTING
ZookeeperApp-1: Creating ZookeeperApp instance
KafkaBrokerApp-2: Creating KafkaBrokerApp instance
KafkaBrokerApp-2: Listeners: PLAINTEXT://localhost:59351
Traceback (most recent call last):
  File "./broker_version_tests.py", line 185, in <module>
    interact=args.interact, debug=args.debug)
  File "./broker_version_tests.py", line 35, in test_it
    debug=debug)
  File "/src/librdkafka-master/tests/cluster_testing.py", line 56, in __init__
    self.brokers.append(KafkaBrokerApp(self, defconf))
  File "build/bdist.linux-x86_64/egg/trivup/apps/KafkaBrokerApp.py", line 75, in __init__
KeyError: 'advertised_listeners'
```
Maybe I miss some information or details in test.conf file ... ?

**Comment by edenhill** [comment]
You need to pull in the latest trivup  (as of 1 minute ago) from git and install that to your virtualenv

**Comment by edenhill** [comment]
Sorry, I see you do that. Anyway, I just pushed so clear your cache and give it another spin

**Comment by albundy83** [comment]
Yes that's much better :)
But, now I got this : 
```bash
ZookeeperApp-1: Environment: defaultdict(<type 'list'>, {'LC_ALL': 'C'})
ZookeeperApp-1: Executing: /src/librdkafka-master/tests/tmp/LibrdkafkaTestCluster/KafkaBrokerApp/kafka/0.8.1.1/bin/zookeeper-server-start.sh /src/librdkafka-master/tests/tmp/LibrdkafkaTestCluster/86663878/ZookeeperApp/1/zookeeper.properties
ZookeeperApp-1: Checking if operational
LibrdkafkaTestCluster: Waiting for 1 apps to go operational: {ZookeeperApp@localhost:1(started)}
ZookeeperApp-1: process terminated: returncode 127
LibrdkafkaTestCluster: 1 apps terminated while waiting to go operational: {ZookeeperApp@localhost:1(stopped)}
Traceback (most recent call last):
  File "./broker_version_tests.py", line 185, in <module>
    interact=args.interact, debug=args.debug)
  File "./broker_version_tests.py", line 46, in test_it
    cluster.start(timeout=30)
  File "build/bdist.linux-x86_64/egg/trivup/trivup.py", line 81, in start
Exception: Cluster did not go operational in 30s
```
I have tried to increase this value, but it does not seems to have an effect ...
# For slow connections: multiply test timeouts by this much (float)
test.timeout.multiplier=80.5

**Comment by edenhill** [comment]
That multiplier only affects the actual test, the trivup cluster timeout is not affected by it, and I dont think it needs to be increased -  something else is probably wrong.
Missing jre/jvm?

Look for clues in the stdout and stderr files here:
/src/librdkafka-master/tests/tmp/LibrdkafkaTestCluster/86663878/ZookeeperApp/1/z

**Comment by albundy83** [comment]
Ah yes, you are right, I'm adding all the missing dependencies.

**Comment by albundy83** [comment]
Here my current Dockerfile, still working on it.
```docker
FROM alpine:3.4

ENV GRADLE_VERSION 2.12
ENV GRADLE_HOME /usr/local/gradle
ENV PATH ${PATH}:${GRADLE_HOME}/bin

RUN apk update \
    && apk add bash curl tar openjdk8 git \
    && apk add --no-cache --virtual .build-deps ca-certificates make gcc g++ python zlib-dev openssl-dev cyrus-sasl-dev lz4-dev libc-dev bsd-compat-headers py-setuptools

ADD https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip /usr/local/gradle.zip

RUN cd /usr/local \
    && unzip gradle.zip \
    && ln -s gradle-$GRADLE_VERSION gradle

WORKDIR /src

ADD https://github.com/edenhill/librdkafka/archive/master.zip /src/librdkafka.zip

RUN unzip librdkafka.zip \
    && cd /src/librdkafka-master \
    && ./configure \
    && make \
    && make install

ADD https://github.com/edenhill/trivup/archive/master.zip /src/trivup.zip

RUN unzip trivup.zip \
    && cd /src/trivup-master \
    && python setup.py install

COPY test.conf /src/librdkafka-master/tests/

RUN cd /src/librdkafka-master/tests \
    && ./broker_version_tests.py --debug
```

**Comment by albundy83** [comment]
So, here a working version, I have ran all tests, some are success, some are not :-)
```docker
FROM alpine:3.4

ENV GRADLE_VERSION 2.12
ENV GRADLE_HOME /usr/local/gradle
ENV PATH ${PATH}:${GRADLE_HOME}/bin

RUN apk update \
    && apk add bash curl tar openjdk8 git sqlite \
    && apk add --no-cache --virtual .build-deps ca-certificates make gcc g++ python zlib-dev openssl-dev cyrus-sasl-dev lz4-dev libc-dev bsd-compat-headers py-setuptools

ADD https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip /usr/local/gradle.zip

RUN cd /usr/local \
    && unzip gradle.zip \
    && ln -s gradle-$GRADLE_VERSION gradle

WORKDIR /src

ADD https://github.com/edenhill/librdkafka/archive/master.zip /src/librdkafka.zip

RUN unzip librdkafka.zip \
    && cd /src/librdkafka-master \
    && ./configure \
    && make \
    && make install

ADD https://github.com/edenhill/trivup/archive/master.zip /src/trivup.zip

RUN unzip trivup.zip \
    && cd /src/trivup-master \
    && python setup.py install

COPY test.conf /src/librdkafka-master/tests/

RUN cd /src/librdkafka-master/tests \
    && make full
```
If you are interested, I could share the results (or you can just use this dockerfile and try... ).
Some errors are related to connection issues problem:
```bash
[0029_assign_offset          /  5.270s] HL.CONSUME: consume 200 messages
%3|1486669515.690|FAIL|0029_assign_offset#consumer-44| [thrd:localhost:55627/bootstrap]: localhost:55627/bootstrap: Connect to ipv6#[::1]:55627 failed: Connection refused
[0029_assign_offset          /  5.280s] TEST FAILURE
### Test "0029_assign_offset" failed at test.c:302:test_error_cb(): ###
rdkafka error: Local: Broker transport failure: localhost:55627/bootstrap: Connect to ipv6#[::1]:55627 failed: Connection refused
### Test random seed was -2119195149 ###
```
or:
```bash
[0033_regex_subscribe_local  /  0.005s] TEST FAILURE
### Test "0033_regex_subscribe_local" failed at 0033-regex_subscribe.c:455:main_0033_regex_subscribe_local(): ###
Test assertion failed: "err == RD_KAFKA_RESP_ERR__INVALID_ARG": invalids failed with wrong return: Success
### Test random seed was 2078624493 ###
```
for some also, it seems that I should have defined some parameters:
```bash
[0044_partition_cnt          /  0.000s] WARN: SKIPPING TEST: Cannot create topics (set KAFKA_PATH and ZK_ADDRESS)
```
Most of them are ending with:
```bash
[<MAIN>                      / 84.012s] TEST FAILURE
### Test "<MAIN>" failed at test.c:574:test_wait_exit(): ###
12 thread(s) still active in librdkafka
### Test random seed was 2078624493 ###
[<MAIN>                      / 84.013s] # Test report written to /src/librdkafka-master/tests/tmp/LibrdkafkaTestCluster/86669400/LibrdkafkaTestApp/54e2d0a9/test_report
[<MAIN>                      / 84.013s] TEST FAILURE
### Test "<MAIN>" failed at test.c:1297:main(): ###
1 test(s) failed, see previous errors
### Test random seed was 2078624493 ###
Assertion failed: 0 (test.c: main: 1297)
./run-test.sh: line 58:  1276 Aborted                 (core dumped) $TEST $ARGS
```

**Comment by edenhill** [comment]
@albundy83 Since you seem to know your way around Alpine, can you have a look at this SO question?: http://stackoverflow.com/questions/43664505/using-confluent-kafka-python-client-in-alpine-container

**Comment by albundy83** [comment]
Sure :-)
http://stackoverflow.com/a/43675634/5244139
