### ISSUE TITLE
md_rand.c:327: ssleay_rand_add: Assertion `md_c[1] == md_count[1]' failed.

### ISSUE THREAD

**Issue by laoshancun** [edenhill/librdkafka#1298]
Description
===========

here is the backtrace.
```
#0  0x0000003678c325e5 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64 

#1  0x0000003678c33dc5 in abort () at abort.c:92 

#2  0x0000003678c2b70e in __assert_fail_base (fmt=<value optimized out>, assertion=0x757197 "md_c[1] == md_count[1]", file=0x75718d "md_rand.c", line=<value optimized out>,
    function=<value optimized out>) at assert.c:96 

#3  0x0000003678c2b7d0 in __assert_fail (assertion=0x757197 "md_c[1] == md_count[1]", file=0x75718d "md_rand.c", line=327, function=0x757250 "ssleay_rand_add") at assert.c:105 

#4  0x000000000064ccd4 in ssleay_rand_add () 

#5  0x00000000005399b3 in ssl23_connect () 

#6  0x00007f7f5f39b0b2 in rd_kafka_transport_ssl_handhsake (rktrans=0x7f7f56d08040, events=1) at rdkafka_transport.c:600 

#7  rd_kafka_transport_io_event (rktrans=0x7f7f56d08040, events=1) at rdkafka_transport.c:1027 

#8  0x00007f7f5f38ef6e in rd_kafka_broker_serve (rkb=0x7f7f7f738000, timeout_ms=10) at rdkafka_broker.c:3224 

#9  0x00007f7f5f38f309 in rd_kafka_broker_ua_idle (rkb=0x7f7f7f738000, timeout_ms=<value optimized out>) at rdkafka_broker.c:3269 

#10 0x00007f7f5f3904f8 in rd_kafka_broker_thread_main (arg=0x7f7f7f738000) at rdkafka_broker.c:4669 

#11 0x00007f7f5f3bfa2f in _thrd_wrapper_function (aArg=<value optimized out>) at tinycthread.c:624 

#12 0x0000003679007aa1 in start_thread (arg=0x7f7ed9964700) at pthread_create.c:301 

#13 0x0000003678ce8aad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115 

(gdb) 
```

How to reproduce
================
use `mistsv/luardkafka` with nginx.
connect kafka with ssl protocol

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): librdkafka-v0.9.5
 - [x] Apache Kafka version: 0.10.2.1
 - [ ] librdkafka client configuration:
 - [x] Operating system:CentOS 6.4
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue
 - [x] openssl version:  openssl-1.0.2c

**Comment by laoshancun** [comment]
thanks,i should recompile my openssl.
