### ISSUE TITLE
segfault with latest kafkacat/librdkafka and Kafka 0.11.0

### ISSUE THREAD

**Issue by LionelCons** [edenhill/librdkafka#1329]
I have built the latest `kafkacat`/`librdkafka` using kafkacat's `bootstrap.sh`.

I got:
```
Version 1.3.1-13-ga6b599 (JSON) (librdkafka 0.11.0-RC1 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins)
```

I am using it contact Kafka brokers using Kerberos and SSL, with the -L option.

For brokers running 0.10.2, `kafkacat` works perfectly well, all the time.

Simply changing the broker queried to one running Kafka 0.11.0, I get segfault most of the time (more than 9 times out of 10).

**Comment by edenhill** [comment]
Ouch.

Can you try to extract a core file?
```
$ ulimit -c unlimited
$ kafkacat ... -make-it-crash
$ gdb kafkacat core
```

**Comment by LionelCons** [comment]
I can ;-)
```
(gdb) bt
#0  0x0000000000000013 in ?? ()
#1  0x00007f83a1e10955 in _sasl_conn_getopt () from /lib64/libsasl2.so.3
#2  0x00007f83a1e0c988 in _sasl_canon_user () from /lib64/libsasl2.so.3
#3  0x00007f83a1e0cc4c in _sasl_canon_user_lookup () from /lib64/libsasl2.so.3
#4  0x00007f839f0056c6 in gssapi_client_mech_step () from /usr/lib64/sasl2/libgssapiv2.so
#5  0x00007f83a1e0f7f5 in sasl_client_step () from /lib64/libsasl2.so.3
#6  0x0000000000489dd3 in rd_kafka_sasl_cyrus_recv (rktrans=0x7f8398000a10, buf=0x7f8398017cf0, size=108, errstr=0x7f839d9df6d0 "", errstr_size=512) at rdkafka_sasl_cyrus.c:73
#7  0x0000000000478a7e in rd_kafka_sasl_io_event (rktrans=0x7f8398000a10, events=<optimized out>, errstr=errstr@entry=0x7f839d9df6d0 "", errstr_size=errstr_size@entry=512) at rdkafka_sasl.c:137
#8  0x000000000043752d in rd_kafka_transport_io_event (rktrans=0x7f8398000a10, events=1) at rdkafka_transport.c:1247
#9  0x000000000043829e in rd_kafka_transport_io_serve (rktrans=<optimized out>, timeout_ms=timeout_ms@entry=999) at rdkafka_transport.c:1311
#10 0x0000000000427998 in rd_kafka_broker_serve (rkb=rkb@entry=0x25a0140, abs_timeout=abs_timeout@entry=10266862396239) at rdkafka_broker.c:2208
#11 0x0000000000427df8 in rd_kafka_broker_ua_idle (rkb=rkb@entry=0x25a0140, timeout_ms=<optimized out>, timeout_ms@entry=-1) at rdkafka_broker.c:2270
#12 0x0000000000428288 in rd_kafka_broker_thread_main (arg=arg@entry=0x25a0140) at rdkafka_broker.c:3119
#13 0x00000000004714c7 in _thrd_wrapper_function (aArg=<optimized out>) at tinycthread.c:624
#14 0x00007f83a2898dc5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007f83a173076d in clone () from /lib64/libc.so.6
```

**Comment by edenhill** [comment]
Is this on Fedora 25 perhaps?
We've seen problems with libsasl plugins there and don't know what the problem is.

**Comment by LionelCons** [comment]
This is on CentOS 7.3.1611.

**Comment by LionelCons** [comment]
FWIW, the problem seems to occur only when the number of bootstrap servers is greater than one.
