### ISSUE TITLE
librdkafka build dependency missing

### ISSUE THREAD

**Issue by peanutpi** [edenhill/librdkafka#1367]
Description
===========
- We are currently using librdkafka as a Node module using [node-rdkafka](https://github.com/Blizzard/node-rdkafka).
- This whole setup runs on a Ubuntu 16.04 LTS OS.
- so when we install all the npm dependencies using `npm isntall`, npm builds librdkafka as well.
- & when we use this there are following logs in the console 

```
make: Entering directory '/home/dev/Work/kudobuzz/socialreviews-apigateway/node_modules/node-rdkafka/build'
  ACTION configuring librdkafka... deps/librdkafka/config.h
checking for OS or distribution... ok (Ubuntu)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x000905ff'... ok (0.9.5)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for zlib (by compile)... ok
checking for libcrypto (by pkg-config)... ok
checking for libcrypto (by compile)... ok
checking for liblz4 (by pkg-config)... ok
checking for liblz4 (by compile)... ok
checking for libssl (by pkg-config)... ok
checking for libssl (by compile)... ok
checking for libsasl2 (by pkg-config)... ok
checking for libsasl2 (by compile)... ok
checking for regex (by compile)... ok
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for strndup (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               Ubuntu
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.9.5
  MKL_APP_VERSION          0.9.5
  LIBS                     -lpthread -lz -lz -lcrypto -lcrypto -llz4 -llz4 -lssl -lssl -lsasl2 -lsasl2 -lrt
  CFLAGS                   
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
Generated config.cache
```

- & after `npm install` successfully finishes, I am able to see a `config.log` in `node_modules/node-rdkafka/deps/librdkafka` , with following content

```
# configure exec: ./configure 
# On Tue Aug  8 18:05:32 IST 2017
DBG: ccenv: WITH_CC:  --version failed: mklove/modules/configure.base: line 1114: --version: command not found
DBG: Check ccenv (WITH_CC, action cont (originally cont)) failed: command ' --version' failed:
mklove/modules/configure.base: line 1114: --version: command not found
DBG: cxxenv: WITH_CXX:  --version failed: mklove/modules/configure.base: line 1114: --version: command not found
DBG: Check cxxenv (WITH_CXX, action cont (originally cont)) failed: command ' --version' failed:
mklove/modules/configure.base: line 1114: --version: command not found
DBG: Compile check PIC (HAVE_PIC): gcc  -g -O2 -Wall -Werror -fPIC _mkltmpTXkTDB.c -o _mkltmpTXkTDB.c.o  
DBG: Compile check gnulib (WITH_GNULD): gcc  -g -O2 -fPIC -Wall -Werror -shared -Wl,-soname,mkltest.0 _mkltmpjpa1p2.c -o _mkltmpjpa1p2.c.o  
DBG: Compile check ldsflagvs (): gcc  -g -O2 -fPIC -Wall -Werror -shared -Wl,--version-script=_mkltmpvr5EXP _mkltmpVTos2q.c -o _mkltmpVTos2q.c.o  
DBG: Compile check __atomic_32 (HAVE_ATOMICS_32): gcc  -g -O2 -fPIC -Wall -Werror  _mkltmpc9CdIQ.c -o _mkltmpc9CdIQ.c.o  
DBG: Compile check __atomic_64 (HAVE_ATOMICS_64): gcc  -g -O2 -fPIC -Wall -Werror  _mkltmpkuJ5yH.c -o _mkltmpkuJ5yH.c.o  
DBG: Compile check socket (): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror  _mkltmpQ3Gb0d.c -o _mkltmpQ3Gb0d.c.o  
DBG: pkg-config check libpthread (): pkg-config --short-errors --cflags libpthread
DBG: 'pkg-config --short-errors --cflags libpthread' failed: No package 'libpthread' found
DBG: Check libpthread_PKGCONFIG (, action cont (originally cont)) failed: 'pkg-config --short-errors --cflags libpthread' failed:
No package 'libpthread' found
DBG: Compile check libpthread (): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror -lpthread _mkltmp5SOa6o.c -o _mkltmp5SOa6o.c.o  
DBG: pkg-config check zlib (): pkg-config --short-errors --cflags zlib
DBG: Compile check zlib (WITH_ZLIB): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror -lz _mkltmpguMP35.c -o _mkltmpguMP35.c.o  
DBG: pkg-config check libcrypto (): pkg-config --short-errors --cflags libcrypto
DBG: Compile check libcrypto (): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror -lcrypto _mkltmp7w3Kg9.c -o _mkltmp7w3Kg9.c.o  
DBG: pkg-config check liblz4 (): pkg-config --short-errors --cflags liblz4
DBG: Compile check liblz4 (WITH_LZ4_EXT): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror -llz4 _mkltmpb8mfmI.c -o _mkltmpb8mfmI.c.o  
DBG: pkg-config check libssl (): pkg-config --short-errors --cflags libssl
DBG: Compile check libssl (WITH_SSL): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror -lssl _mkltmpPdRWSA.c -o _mkltmpPdRWSA.c.o  
DBG: pkg-config check libsasl2 (): pkg-config --short-errors --cflags libsasl2
DBG: Compile check libsasl2 (WITH_SASL): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror -lsasl2 _mkltmp61L5xa.c -o _mkltmp61L5xa.c.o  
DBG: Compile check regex (HAVE_REGEX): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror  _mkltmpR5g98Z.c -o _mkltmpR5g98Z.c.o  
DBG: pkg-config check librt (): pkg-config --short-errors --cflags librt
DBG: 'pkg-config --short-errors --cflags librt' failed: No package 'librt' found
DBG: Check librt_PKGCONFIG (, action cont (originally cont)) failed: 'pkg-config --short-errors --cflags librt' failed:
No package 'librt' found
DBG: Compile check librt (): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror -lrt _mkltmpg5jloH.c -o _mkltmpg5jloH.c.o  
DBG: Compile check strndup (HAVE_STRNDUP): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror  _mkltmpKQEVrr.c -o _mkltmpKQEVrr.c.o
```
- And we are not able to connect to kafka & there is no logs as well in the console of any error. So we go through all the logs & we found above logs.
- So it tell that there are some package that are not found on my machine.
- I've also tried to install that packages using following command, but the issue still persist.

```
sudo apt-get install libpthread-stubs0-dev
sudo apt-get install liblz4-dev
```

- librdkafka version : 0.9.5
- Kafka version : 0.9.0.1
- client config : 

```
// Automatically generated by ./configure 
#pragma once
#define ARCH "x86_64"
#define CPU "generic"
#define WITHOUT_OPTIMIZATION 0
#define ENABLE_DEVEL 0
#define ENABLE_VALGRIND 0
#define ENABLE_REFCNT_DEBUG 0
#define ENABLE_SHAREDPTR_DEBUG 0
#define ENABLE_LZ4_EXT 1
#define ENABLE_SSL 1
#define ENABLE_SASL 1
#define MKL_APP_NAME "librdkafka"
#define MKL_APP_DESC_ONELINE "The Apache Kafka C/C++ library"
// gcc
#define WITH_GCC 1
// gxx
#define WITH_GXX 1
// pkgconfig
#define WITH_PKGCONFIG 1
// install
#define WITH_INSTALL 1
// PIC
#define HAVE_PIC 1
// gnulib
#define WITH_GNULD 1
// __atomic_32
#define HAVE_ATOMICS_32 1
// __atomic_32
#define HAVE_ATOMICS_32_ATOMIC 1
// atomic_32
#define ATOMIC_OP32(OP1,OP2,PTR,VAL) __atomic_ ## OP1 ## _ ## OP2(PTR, VAL, __ATOMIC_SEQ_CST)
// __atomic_64
#define HAVE_ATOMICS_64 1
// __atomic_64
#define HAVE_ATOMICS_64_ATOMIC 1
// atomic_64
#define ATOMIC_OP64(OP1,OP2,PTR,VAL) __atomic_ ## OP1 ## _ ## OP2(PTR, VAL, __ATOMIC_SEQ_CST)
// atomic_64
#define ATOMIC_OP(OP1,OP2,PTR,VAL) __atomic_ ## OP1 ## _ ## OP2(PTR, VAL, __ATOMIC_SEQ_CST)
// parseversion
#define RDKAFKA_VERSION_STR "0.9.5"
// parseversion
#define MKL_APP_VERSION "0.9.5"
// zlib
#define WITH_ZLIB 1
// liblz4
#define WITH_LZ4_EXT 1
// WITH_SNAPPY
#define WITH_SNAPPY 1
// WITH_SOCKEM
#define WITH_SOCKEM 1
// libssl
#define WITH_SSL 1
// libsasl2
#define WITH_SASL 1
// regex
#define HAVE_REGEX 1
// strndup
#define HAVE_STRNDUP 1
// python
#define HAVE_PYTHON 1
```

- OS : ubuntu 16.04

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
 - [x] Apache Kafka version: 
 - [x] librdkafka client configuration:
 - [x] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
I think the configure phase looks fine, [mklove](https://github.com/edenhill/mklove) uses multiple methods to find libraries, such as with pthreads:

```
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
```
first with pkg-config, then by a straight up compile attempt.


What are the actual problems you are seeing?

**Comment by peanutpi** [comment]
Thanks for the quick reply. we are not able to connect to kafka broker running on remote machine with security protocol ssl.

**Comment by edenhill** [comment]
Provide sanitized client config properties (not build config) and any log
messages seen.
You can also enable security debugging by setting the debug property to
"security"

Den 8 aug 2017 18:35 skrev "Pratik" <notifications@github.com>:

**Comment by peanutpi** [comment]
Sorry for the misunderstanding, This is my client config
```
{
  'compression.codec': 'gzip',
  'request.required.acks': 1,
  'client.id': 'client1',
  'metadata.broker.list': 'kafka:9093',
  debug: 'security',
  'ssl.certificate.location': '/path/to/kafka.cert',
  'ssl.key.location': '/path/to/kafka.key',
  'ssl.ca.location': '/path/to/kafka.ca',
  'security.protocol': 'ssl' 
}
```
even after enabling `security` logs I am not able to see any logs.

**Comment by treziac** [comment]
What do you mean exactly by "not seeing any log", is your application correctly starting?

In node rdkafka, you have to register to get events, via `producer.on("event.log", ...)` and "event.error"
https://github.com/Blizzard/node-rdkafka#events
Did you do that?

Can you post your code?

**Comment by peanutpi** [comment]
After a little debugging & adding a callback I got follwoing error
```
 { Error: ssl.ca.location failed: No error
    at Function.createLibrdkafkaError [as create] (/project/node_modules/node-rdkafka/lib/error.js:260:10)
    at /project/node_modules/node-rdkafka/lib/client.js:182:28
  message: 'ssl.ca.location failed: No error',
  code: -172,
  errno: -172,
  origin: 'kafka' }
```

**Comment by treziac** [comment]
This seems related to #1218 , but those were sporadic error which did not prevent connexion or message sending (simple timeouts on unused broker)
Can you set debug to 'broker,security' and post revelant logs, and also check your broker logs?

Do you manage to connect using the kafka console producer?

Do you have any endpoint not using ssl to check if it is working properly?

**Comment by peanutpi** [comment]
@treziac : I guess we don't have any endpoint not using ssl. & no I've not tried using console producer. I'll try that & ping you. & I've also tried to set `debug` with all the possible options, but don't get anything in the logs.

**Comment by peanutpi** [comment]
I am sorry for the extra code , but I don't know much of js. I am a DevOps.

The code where we are configuring event
```js
‘use strict’
const debug = require(‘debug’)(‘queue:event’)

const onReady = ({connection, emitter}) => (info, metadata) => {
  debug(‘ready:info: ‘, info)
  const options = {timeout: 5000}

 connection.getMetadata(options, (err, metadata) => {
    if (metadata) {
      debug(‘connection:isconnected’)
      return emitter.emit(‘connected’)
    }

   if (err) {
      debug(‘connection:metadata:err’, metadata)
    }

   emitter.disconnect()
  })
}

const onError = ({emitter}) => err => {
  debug(‘event:error’, err)
  emitter.disconnect()
}

const onDisconnected = ({emitter}) => (err, data) => {
  debug(‘disconnected:‘, err, data)
  emitter.emit(‘disconnected’)
}

const onEventLog = event => {
  debug(‘event:log’, event)
}

module.exports = {
  add ({connection, emitter, name}) {
    connection
      .on(‘event.error’, onError({emitter}))
      .on(‘ready’, onReady({emitter, connection}))
      .on(‘disconnected’, onDisconnected({emitter}))
      .on(‘event.log’, onEventLog)

   return connection
  }
}
```

the actual code where we are connecting to kafka using 
```js
const EventEmitter = require('events').EventEmitter
const debug = require('debug')('queue:producer')
const DEFAULT_OPTIONS = require('./defaultOptions')
const addEventListener = require('./addEventListeners').add
const {Producer: KafkaProducer} = require('node-rdkafka')
const config = require('../config')
const {createPublisher} = require('./publisher')

const KAFKA_HOST = config('QUEUE_URL')
const POLL_TIME = 100
let producerConnection
let producer = Object.create(EventEmitter.prototype)
EventEmitter.call(producer)

debug(`kafka broker list: ${KAFKA_HOST}`)

const DEFAULT_PRODUCER_OPTIONS = Object.assign(
  {
    'dr_cb': true,
    'compression.codec': 'gzip',
    'request.required.acks': 1
  },
  DEFAULT_OPTIONS
)
const onDeliveryReport = ({producer}) => (err, data) => {
  if (err) {
    debug('delivery-report:error', err)
  } else {
    debug('delivery-report:received', data)
    producer.emit('sent', data)
  }
}

function kafkaProducer ({options} = {}) {
  return Object.assign(producer, {
    name: 'Producer',
    isConnected () {
      return producerConnection && producerConnection.isConnected()
    },

    connect () {
      if (!producer.isConnected()) {
        const PRODUCER_OPTIONS = Object.assign(DEFAULT_PRODUCER_OPTIONS, options)

        producerConnection = new KafkaProducer(PRODUCER_OPTIONS)
        producerConnection.setPollInterval(POLL_TIME)

        debug('polltime', POLL_TIME)
        debug('options', PRODUCER_OPTIONS)

        addEventListener({connection: producerConnection, emitter: producer})
        .on('delivery-report', onDeliveryReport({producer}))
        .connect(null, function(err,data){console.log("Connection Callback ----->>>>",err,data)})
        
        debug('Producer : ', producer.isConnected())
      }
      return producer
    },
    disconnect () {
      if (producer.isConnected()) {
        producerConnection.disconnect()
      }
      return producer
    }
  })
}

module.exports = {
  kafkaProducer,
  publish ({payload, topicOptions, partition, key}) {
    if (producerConnection && producerConnection.isConnected()) {
      createPublisher({producer: producerConnection})({payload, topicOptions, partition, key})
    } else {
      debug('producer is not connected')
      // todo: this should be an event emitter so that we dont have to do this
      setTimeout(() => {
        producer.emit('error', new Error('producer is not connected'))
      }, 1000)
    }
    return producer
  }
}

```

**Comment by edenhill** [comment]
"ssl.ca.location failed: .." means the underlying call to OpenSSL's [SSL_CTX_load_verify_locations](https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_load_verify_locations.html) failed, which is typically because the certs could not be found, read (permissions) or is in the wrong format.

Do note that you can't use the Java client config directly, you need settings and files compatible with OpenSSL. See this wiki for more info: https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

The "No error" message is fixed in librdkafka v0.11.0 through this commit: https://github.com/edenhill/librdkafka/commit/9f289d36cd26320ff2ece7571e52ec4e82e69de9

**Comment by peanutpi** [comment]
@edenhill : thanks you are right, found the issue, the cert, key files were having \n instead of new line. I guess which is causing this error. so that resolved the issue. 

Thank you once again for the help. I am closing this issue.

**Comment by mkscastillo** [comment]
> After a little debugging & adding a callback I got follwoing error
> 
> ```
>  { Error: ssl.ca.location failed: No error
>     at Function.createLibrdkafkaError [as create] (/project/node_modules/node-rdkafka/lib/error.js:260:10)
>     at /project/node_modules/node-rdkafka/lib/client.js:182:28
>   message: 'ssl.ca.location failed: No error',
>   code: -172,
>   errno: -172,
>   origin: 'kafka' }
> ```

What callback did you have to add ?
