### ISSUE TITLE
Unexpected Kafka request of type METADATA during SASL handshake

### ISSUE THREAD

**Issue by dmag1** [edenhill/librdkafka#1584]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We have Kafka cluster with Kerberos authentication enabled. While we are using librdkafka as producer for a given topic the above issue is thrown. This is quite similar to [issue](https://github.com/dpkp/kafka-python/issues/1189).

How to reproduce
================
rdkafka_example -P -t <topic> -b <broker> -X sasl.kerberos.service.name=kafka -X sasl.kerberos.principal=<kerberos.principal> -X sasl.kerberos.keytab=<kerberos.keytab>

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [ ] librdkafka version :  0.11.0 (0x000b00ff)
 - [ ] Apache Kafka version: 0.10.0.0
 - [ ] librdkafka client configuration: `default
 - [ ] Operating system: Opensuse 42.2 x86_64 (Linux x86_64 Linux in general)
 - [ ] Provide logs

12476945.430 RDKAFKA-3-FAIL: rdkafka#producer-1: [thrd:<broker-ip>:9092/bootstrap]: <broker-ip>:9092/bootstrap: Receive failed: Disconnected
1512476945.430 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:<broker-ip>:9092/bootstrap]: <broker-ip>:9092/bootstrap: Receive failed: Disconnected

 - [ ] Provide broker log excerpts

2017-12-05 17:59:18,996 DEBUG org.apache.kafka.common.network.Selector: Connection with /X.X.X.X disconnected
java.io.IOException: org.apache.kafka.common.errors.IllegalSaslStateException: Unexpected Kafka request of type METADATA during SASL handshake.
	at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:243)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:64)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:318)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:283)
	at kafka.network.Processor.poll(SocketServer.scala:472)
	at kafka.network.Processor.run(SocketServer.scala:412)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.IllegalSaslStateException: Unexpected Kafka request of type METADATA during SASL handshake.
 
- [ ] Critical issue : kind of showstopper from our perspective

**Comment by edenhill** [comment]
You need to specify `security.protocol=sasl_plaintext` too
