### ISSUE TITLE
Producer retry when the broker encounter shutdown?

### ISSUE THREAD

**Issue by sheeysong** [edenhill/librdkafka#1812]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We are using linrdkafka 0.11.0, broker version 0.11.0 with config ACK=1 (leader ACK), total 5-broker cluster, replica=2.
For some reason -- our broker5 short of memory, and the node went down. Somehow our Go-client not publishing to the remaining 4-node cluster any more. (active node=4 > replica=2).
per document -- message.send.max.retrie=2, retry interval is 100ms.

When publish messages, we have key, so use key hash against the cluster nodes. I expect the dead node shall be removed from the client cache, so publishing shall still get going. However, it wasn't that case.
please let me know it's bug or we missed something.

How to reproduce
================
keep the client publishing messages and meanwhile shutdown a broker node

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.0`
 - [ ] Apache Kafka version: `<0.11.0>`
 - [ ] librdkafka client configuration: `<ACK=1, retry using default setting>`
 - [ ] Operating system: `Ubuntu 14.04.4 LTS`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
[2018-05-15 09:23:00,524] WARN [ReplicaFetcherThread-2-5]: Error in fetch to broker 5, request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={activity-625=(offset=57930, logStartOffset=57738, maxBytes=4500054), activity-385=(offset=58260, logStartOffset=58058, maxBytes=4500054), activity-145=(offset=57920, logStartOffset=57732, maxBytes=4500054), activity-785=(offset=57674, logStartOffset=57497, maxBytes=4500054), search_features-130=(offset=0, logStartOffset=0, maxBytes=4500054), activity-545=(offset=58110, logStartOffset=57906, maxBytes=4500054), activity-305=(offset=58104, logStartOffset=57930, maxBytes=4500054), fb-78=(offset=301915, logStartOffset=301915, maxBytes=4500054), activity-945=(offset=58066, logStartOffset=57851, maxBytes=4500054), activity-65=(offset=58229, logStartOffset=58049, maxBytes=4500054), activity-705=(offset=57684, logStartOffset=57471, maxBytes=4500054), search_features-50=(offset=0, logStartOffset=0, maxBytes=4500054), activity-465=(offset=57832, logStartOffset=57667, maxBytes=4500054), activity-225=(offset=58149, logStartOffset=57934, maxBytes=4500054), activity-865=(offset=58021, logStartOffset=57839, maxBytes=4500054), heartbeat_fed-68=(offset=0, logStartOffset=0, maxBytes=4500054)}) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 5 was disconnected before the response was read
        at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:93)
        at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:93)
        at kafka.server.ReplicaFetcherThread.fetch(ReplicaFetcherThread.scala:207)
        at kafka.server.ReplicaFetcherThread.fetch(ReplicaFetcherThread.scala:42)
        at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:151)
        at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:112)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:64)
[2018-05-15 09:23:00,764] INFO [ReplicaFetcherThread-6-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,764] INFO [ReplicaFetcherThread-6-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,766] INFO [ReplicaFetcherThread-0-5]: Shutting down (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,766] INFO [ReplicaFetcherThread-0-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,766] INFO [ReplicaFetcherThread-0-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,767] INFO [ReplicaFetcherThread-3-5]: Shutting down (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,767] INFO [ReplicaFetcherThread-3-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,767] INFO [ReplicaFetcherThread-3-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,768] INFO [ReplicaFetcherThread-2-5]: Shutting down (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,768] INFO [ReplicaFetcherThread-2-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,768] INFO [ReplicaFetcherThread-2-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,770] INFO [ReplicaFetcherThread-7-5]: Shutting down (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,770] INFO [ReplicaFetcherThread-7-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,770] INFO [ReplicaFetcherThread-7-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:00,771] INFO [ReplicaFetcherThread-14-5]: Shutting down (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:16,813] INFO [ReplicaFetcherThread-14-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:16,813] INFO [ReplicaFetcherThread-14-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:16,815] INFO [ReplicaFetcherThread-4-5]: Shutting down (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:16,815] INFO [ReplicaFetcherThread-4-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:16,815] INFO [ReplicaFetcherThread-4-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:16,816] INFO [ReplicaFetcherThread-12-5]: Shutting down (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:16,816] INFO [ReplicaFetcherThread-12-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:16,816] INFO [ReplicaFetcherThread-12-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:16,818] INFO [ReplicaFetcherThread-8-5]: Shutting down (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:22,798] INFO [ReplicaFetcherThread-8-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:22,798] INFO [ReplicaFetcherThread-8-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:22,802] INFO [ReplicaFetcherThread-15-5]: Shutting down (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:22,802] INFO [ReplicaFetcherThread-15-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:22,802] INFO [ReplicaFetcherThread-15-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:22,802] INFO [ReplicaFetcherThread-11-5]: Shutting down (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:22,802] INFO [ReplicaFetcherThread-11-5]: Stopped (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:22,802] INFO [ReplicaFetcherThread-11-5]: Shutdown completed (kafka.server.ReplicaFetcherThread)
[2018-05-15 09:23:22,802] INFO [ReplicaFetcherThread-10-5]: Shutting down (kafka.server.ReplicaFetcherThread)
 - [ ] Critical issue
The Go-client stop publishing any more when a node was shutdown (repeat with kill -9 PID)

**Comment by rnpridgeon** [comment]
After the node was shutdown was a new leader elected? 

It's possible that the follower had already fallen out of the ISR. If this happened prior to node 5 going down and you have unclean leader election disabled (disabled by default as of 0.11) then the follower cannot be elected as a new leader. This would result in the topic partition being marked as offline and thus the producer would not be able to produce to it. 

I recommend reviewing the `controller.log` from the presiding controller at the time of the incident along with the `state-change.log` from each broker that maintains a replica for the partition in question.

**Comment by sheeysong** [comment]
Thanks for the quick response!
1. I had checked the controller.log: controller remain as it was -- as the shutdown node is not a controller.
2. Our replica=2, regarding "the follower had already fallen out of the ISR" -- I don't have the trace on this hypothesis. How do I avoid ISR, do I have to set replica more to be safe? say repica=3 or 4?

3. I saw the state.log: In this case, we shutdown broker6 to reproduce the problem. When replica on broker6, it showed ---"Broker 1 cached leader info"

[2018-05-20 17:58:39,850] TRACE Broker 1 cached leader info (LeaderAndIsrInfo:(Leader:3,ISR:3,LeaderEpoch:4,ControllerEpoch:12),ReplicationFactor:2),AllReplicas:6,3) for partition image_dedup-62 in response to UpdateMetadata request sent by controller 2 epoch 12 with correlation id 7633 (state.change.logger)

then --
[2018-05-20 17:58:40,484] TRACE Broker 1 received LeaderAndIsr request PartitionState(controllerEpoch=12, leader=1, leaderEpoch=4, isr=1, zkVersion=7, replicas=1,6) correlation id 7634 from controller 2 epoch 12 for partition [activity,37] (state.change.logger)

Can you help decipher the above log?

**Comment by sheeysong** [comment]
Well, I guess we did lost leader per leader=-1 in the log, what is leader=-1 means?

[2018-05-20 17:58:40,493] TRACE Broker 1 cached leader info (LeaderAndIsrInfo:(Leader:-1,ISR:6,LeaderEpoch:4,ControllerEpoch:12),ReplicationFactor:2),AllReplicas:6,5) for partition activity-126 in response to UpdateMetadata request sent by controller 2 epoch 12 with correlation id 7635 (state.change.logger)

How do I avoid lost leader in this case?

Thanks,

**Comment by rnpridgeon** [comment]
A leader of `-1` means that the partition has been marked as offline. This means you will not be able to produce or consume from that partition until it has been brought back online.

To safeguard against this kind of issue we typically recommend that you set `default.replication.factor=3` and `min.insync.replics=2`(broker configs). This ensures that you can continue to produce messages even if one broker is down while ensuring there is still another replica in sync with the leader. 

Prior to restarting brokers I recommend checking the status of the topic as well you can do this with the following command. 

`kafka-topics --describe --zookeeper <zookeeper_host:zookeeper_port> --topic <topic_name>` 

Note: if you are using the Apache Kafka distribution it will be `kafka-topics.sh` as opposed to `kafka-topics`

**Comment by sheeysong** [comment]
Thank you so much for the prompt response!
I have two questions --
1. bin/kafka-configs.sh : can’t use to add "--alter --config default.replication.factor=3 " to override on replica
2. bin/kafka-topics.sh: can’t combine —config  or —alter to change --replication-factor to 3.

We have 200 partitions on this Topic; --replica-assignment is difficult to do.
At the end, I deleted the Topic, however:
When I described the Topic, its shows: MarkedForDeletion:true, and I can't re-create the Topic with the same name.

Please instruct --
1. What shall be the correct command to alter --replication-factor
2. What is the fast way to walk around this issue?

**Comment by sheeysong** [comment]
After raised replicas to 3, things did went better, didn't see leader=-1 any more. However, we discovered there is around 5 mins "pause" on publishing messages, after 5 mins, finally the publishing rate caught up with the original rate.
Are there options that we can shorten this 5 mins?

Also - I would like to confirm that -- by default, librdkafka has 2 retries? reconnect to the broker after the broker back online
Thanks,
~Jing

**Comment by edenhill** [comment]
This is fixed on librdkafka master.
