### ISSUE TITLE
Consumer threads generate coredump when consuming a large mount of data 

### ISSUE THREAD

**Issue by xkzhao** [edenhill/librdkafka#1920]
Description
===========
I created three consumer threads. Every thread read one topic data from kafka. When the amount of  log data to be consumed becomes large , the consumer code will generate core dump. The following is my consumer thread code . 

```
// Thread Entry Function
1189 void * readTopicData(void* context){ 
1190    struct confParams * allConf = (struct confParams  * ) context;
1191    RdKafka::Conf * conf = allConf->conf;
1192    std::vector<std::string> topics;
1193    topics.push_back(allConf->topic);
1194    int run_tm = allConf->run_tm;
1195    int use_ccb = allConf->use_ccb;
1196 
1197   /*
1198    * Consumer mode
1199    */
1200 
1201   /*
1202    * Create consumer using accumulated global configuration.
1203    */
1204   std::string errstr;
1205   RdKafka::KafkaConsumer *consumer = RdKafka::KafkaConsumer::create(conf, errstr);
1206   if (!consumer) {
1207     std::cerr << "Failed to create consumer: " << errstr << std::endl;
1208     pthread_exit(NULL);
1209   }
1210 
1211   std::cout << "% Created consumer " << consumer->name() << std::endl;
1212 
1213 
1214   /*
1215    * Subscribe to topics
1216    */
1217   RdKafka::ErrorCode err = consumer->subscribe(topics);
1218   if (err) {
1219     std::cerr << "Failed to subscribe to " << topics.size() << " topics: "
1220               << RdKafka::err2str(err) << std::endl;
1221     pthread_exit(NULL);
1222   }
1223 
1224   /*
1225    * Consume messages
1226    */
1227   long msg_cnt = 0;
1228   int64_t msg_bytes = 0;
1229   //std::cout << "run_tm=" << run_tm <<std::endl;
1230   int stat_tm = 60; //second
1231   struct timeval tvBegin, tvEnd, tvDiff;
1232   gettimeofday(&tvBegin, NULL);
1233   long num = 0;
1234   while (run) {
1235     RdKafka::Message *msg = consumer->consume(1000);
1236     if (msg == NULL){
1237         continue;
1238     }
1239     int errcode = msg->err();
1240     std::string topic_name = msg->topic_name();
1241     std::string errstr = msg->errstr();
1242 
1243     if (errcode != RdKafka::ERR_NO_ERROR){
1244         //std::cerr << "Consume failed: " << errstr << "," << errcode <<std::endl;
1245         if (msg != NULL){
1246             delete msg;
1247         }
1248         continue;
1249     }
1250     num += 1;
1251 
1252    std::string msgstr( static_cast<const char *>(msg->payload()), static_cast<int>(msg->len()));
1253     if (msg != NULL){
1254         delete msg;
1255     }
1256     if (!use_ccb) { // use_ccb = 0
1257         msg_consume(msgstr, errcode, errstr, topic_name, NULL, msg_cnt, msg_bytes);
1258     }
1259     gettimeofday(&tvEnd, NULL);
1260     uint32_t diff = (tvEnd.tv_sec - tvBegin.tv_sec) * 1000 + (tvEnd.tv_usec -  tvBegin.tv_usec) / 1000;
1261 
1262     if(diff >= stat_tm * 1000) {
1263         std::time_t ts_time = time(NULL);
1264         std::string ts_str = timeStampToHReadble(ts_time);
1265         std::cout << "msg_consume_stat_minu," << ts_str << "," << allConf->topic <<","<< msg_cnt << "," << num << "," << msg_bytes <<std::en     dl;
1266         msg_cnt = 0;
1267         msg_bytes = 0;
1268         num = 0;
1269         gettimeofday(&tvBegin, NULL);
1270     }
1271 
1272   }
1273 
1274 #ifndef _MSC_VER
1275   alarm(10);
1276 #endif
1277 
1278   /*
1279    * Stop consumer
1280    */
1281   consumer->close();
1282   delete consumer;
1283 
1284   if (!use_ccb) { // use_ccb = 0
1285     std::cerr << "% Consumed " << msg_cnt << " messages ("
1286         << msg_bytes << " bytes)"  << " from " << allConf->topic << " topic" << std::endl;
1287     //pthread_exit(NULL);
1288   }
1289 
1290 }
```
Core dump is generated at the  1252 line. 
`1252     std::string msgstr( static_cast<const char *>(msg->payload()), static_cast<int>(msg->len()));`

The following is the backtrace of core dump file .
```
(gdb) bt 
#0  0x00007f621c0345bd in malloc_consolidate () from /lib64/libc.so.6
#1  0x00007f621c0363a5 in _int_malloc () from /lib64/libc.so.6
#2  0x00007f621c03910c in malloc () from /lib64/libc.so.6
#3  0x00007f621c8f40cd in operator new(unsigned long) () from /lib64/libstdc++.so.6
#4  0x00007f621c952c69 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) () from /lib64/libstdc++.so.6
#5  0x00007f621c954521 in char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag) () from /lib64/libstdc++.so.6
#6  0x00007f621c9545dd in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&) () from /lib64/libstdc++.so.6
#7  0x000000000040c9d5 in readTopicData (context=0x7ffcc7aa5380) at consume_test.cpp:1252
#8  0x00007f621d0b9e25 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f621c0b135d in clone () from /lib64/libc.so.6
```

Any idea as to what I might be doing wrong ?

How to reproduce
================

Create multiple consumer thread, every thread has its own topic conf and Consumer object. Try to consume a large mount of data from kafka.

Checklist
=========
 - [x] librdkafka version (release number or git tag): `v0.11.0`
 - [x] Apache Kafka version: `0.10.2.1`
 - [x] librdkafka client configuration: `using default topic conf `
 - [x] Operating system: `CentOS 7.0.1406`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Is this reproducible with librdkafka v0.11.5?
Is the process killed because the amount of available memory on the system is exhausted?
How much memory is the process using before dying?
