### ISSUE TITLE
"rdkafka_consumer_example.cpp" segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ouliuquan** [edenhill/librdkafka#2083]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi, I found that the C++ example "rdkafka_consumer_example.cpp" , I had test several time, find out there is a segmentation fault (core dumped) problem, which I can't solve.

And at the same time, I also test the C example "rdkafka_consumer_example.c", it worked well.

How to reproduce
================
I compile with g++ ( redhat & ubuntu both test) :
g++ -std=c++11 -o rdkafka_consumer_example rdkafka_consumer_example.cpp -lrdkafka++

Checklist
=========
 - [x] librdkafka version v0.11.6
 - [x] Apache Kafka version: `2.11_1.1.0`
 - [x] librdkafka client configuration: `./rdkafka_consumer_example -g cons1 -b localhost:9092 test_topic`
 - [x] CentOS 7 & Ubuntu 18.04
 - [x] Provide logs segmentation fault (core dumped) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need to provide output from gdb:
```
$ gdb ./rdkafka_consumer_example

**Comment by ouliuquan** [comment]
set args -g conser1 -b 10.1.1.141:9092 test_topic -d all
(gdb) r
Starting program: /home/ouliuquan/kafka/./rdkafka_consumer_example -g conser1 -b 10.1.1.141:9092 test_topic -d all
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
2018-11-02 19:18:20.499: LOG-7-MEMBERID: [thrd:app]: Group "conser1": updating member id "(not-set)" -> ""
[New Thread 0x7ffff2d4e700 (LWP 26074)]
[New Thread 0x7ffff254d700 (LWP 26075)]
2018-11-02 19:18:20.503: LOG-7-WAKEUPFD: [thrd:app]: 10.1.1.141:9092/bootstrap: Enabled low-latency partition queue wake-ups
2018-11-02 19:18:20.503: LOG-7-WAKEUPFD: [thrd:app]: 10.1.1.141:9092/bootstrap: Enabled low-latency ops queue wake-ups
2018-11-02 19:18:20.503: LOG-7-BRKREASSIGN: [thrd:main]: Group "conser1" management reassigned from broker (none) to :0/internal
2018-11-02 19:18:20.503: LOG-7-BRKMAIN: [thrd::0/internal]: :0/internal: Enter main broker thread
2018-11-02 19:18:20.503: LOG-7-CGRPSTATE: [thrd:main]: Group "conser1" changed state init -> wait-broker (v1, join-state init)
2018-11-02 19:18:20.503: LOG-7-STATE: [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
2018-11-02 19:18:20.503: LOG-7-BROADCAST: [thrd:main]: Broadcasting state change
2018-11-02 19:18:20.503: LOG-7-BROADCAST: [thrd::0/internal]: Broadcasting state change
2018-11-02 19:18:20.503: LOG-7-BRKASSIGN: [thrd:main]: Group "conser1" management assigned to broker :0/internal
[New Thread 0x7ffff1d4c700 (LWP 26076)]
2018-11-02 19:18:20.504: LOG-7-BROKER: [thrd:app]: 10.1.1.141:9092/bootstrap: Added new broker with NodeId -1
2018-11-02 19:18:20.504: LOG-7-INIT: [thrd:app]: librdkafka v0.11.5 (0xb05ff) rdkafka#consumer-1 initialized (debug 0xffff)
2018-11-02 19:18:20.504: % Created consumer rdkafka#consumer-1
LOG-7-BRKMAIN: [thrd:10.1.1.141:9092/bootstrap]: 10.1.1.141:9092/bootstrap: Enter main broker thread
2018-11-02 19:18:20.504: LOG-7-CONNECT: [thrd:10.1.1.141:9092/bootstrap]: 10.1.1.141:9092/bootstrap: broker in state INIT connecting

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff79103e8 in __dynamic_cast () from /lib64/libstdc++.so.6
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-gssapi-2.1.26-21.el7.x86_64 cyrus-sasl-lib-2.1.26-21.el7.x86_64 cyrus-sasl-md5-2.1.26-21.el7.x86_64 cyrus-sasl-plain-2.1.26-21.el7.x86_64 cyrus-sasl-scram-2.1.26-21.el7.x86_64 glibc-2.17-196.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libdb-5.3.21-20.el7.x86_64 libgcc-4.8.5-16.el7.x86_64 librdkafka-0.11.5-1.el7.x86_64 libselinux-2.5-11.el7.x86_64 libstdc++-4.8.5-16.el7.x86_64 lz4-1.7.3-1.el7.x86_64 nss-softokn-freebl-3.28.3-6.el7.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt full
#0  0x00007ffff79103e8 in __dynamic_cast () from /lib64/libstdc++.so.6
No symbol table info available.
#1  0x00007ffff7bcbf66 in RdKafka::HandleImpl::set_log_queue(RdKafka::Queue*) () from /lib64/librdkafka++.so.1
No symbol table info available.
#2  0x0000000000402c33 in main (argc=8, argv=0x7fffffffe2c8) at rdkafka_consumer_example.cpp:416
        consumer = 0x6086d0
        err = 1633906540
        brokers = "10.1.1.141:9092"
        errstr = ""
        mode = ""
        debug = "all"
        tconf = 0x6086d0
        topic_str = ""
        topics = std::vector of length 1, capacity 1 = {"test_topic"}
        do_conf_dump = false
        opt = -1
        conf = 0x608040
        ex_rebalance_cb = {<RdKafka::RebalanceCb> = {
            _vptr.RebalanceCb = 0x404f30 <vtable for ExampleRebalanceCb+16>}, <No data fields>}
        ex_event_cb = {<RdKafka::EventCb> = {_vptr.EventCb = 0x404f70 <vtable for ExampleEventCb+16>}, <No data fields>}
(gdb)

**Comment by ouliuquan** [comment]
@edenhill Hi, the gdb info had been paste, thanks for the debug.

**Comment by edenhill** [comment]
Thank you.
It seems like it is linking with a system-installed librdkafka in /lib/.., which is odd seeing how the program should be linked statically.
Have you made any changes to the code or build steps?

Can you try removing the system installed librdkafka?

**Comment by ouliuquan** [comment]
Hi, my commany is closed at the weekend, it seems that I have to do this at next Monday.
