### ISSUE TITLE
Crashed in strdup

### ISSUE THREAD

**Issue by prehistoric-penguin** [edenhill/librdkafka#2264]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
The rdkafka producer crashed in libc function `strdup` because the parameter is NULL.

```
#0  0x00002af2a4b74b71 in __strlen_sse2 () from /this/is/a/internal/path/Linux/install/lib/libc.so.6
#1  0x00002af2a4b7487e in strdup () from /this/is/a/internal/path/Linux/install/lib/libc.so.6
#2  0x00002af2bfdf547f in rd_strdup (s=<optimized out>) at rd.h:117
#3  rd_kafka_topic_scan_all (rk=rk@entry=0x8d88860, now=5160346799611) at rdkafka_topic.c:1160
#4  0x00002af2bfdd15d6 in rd_kafka_topic_scan_tmr_cb (rkts=<optimized out>, arg=<optimized out>) at rdkafka.c:1194
#5  0x00002af2bfdf7d28 in rd_kafka_timers_run (rkts=rkts@entry=0x8d89020, timeout_us=timeout_us@entry=0) at rdkafka_timer.c:251
#6  0x00002af2bfdd8317 in rd_kafka_thread_main (arg=arg@entry=0x8d88860) at rdkafka.c:1270
#7  0x00002af2bfe38807 in _thrd_wrapper_function (aArg=<optimized out>) at tinycthread.c:624
#8  0x00002af2a48d9dc5 in _L_lock_26 () from /this/is/a/internal/path/lib64/libpthread-2.12.so
#9  0x00002af2a48d9dca in _L_lock_26 () from /this/is/a/internal/path/lib64/libpthread-2.12.so
#10 0x00002af2a48d9b5f in pthread_getattr_np () from /this/is/a/internal/path/lib64/libpthread-2.12.so
#11 0x0000000000000000 in ?? ()
```
This seems like a bug in rdkafka, do we need to add a check before use `strdup` to make sure the string is not NULL?

How to reproduce
================
Not know not to reproduce.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v0.11.4>`
 - [x] Apache Kafka version: `<kafka_2.11-1.1.0>`
 - [ ] librdkafka client configuration: `<Not very clear, basically we set boot strap server, batch size and timeout>`
 - [x] Operating system: `<RedHat 7.3>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by prehistoric-penguin** [comment]
Close this issue since we find that it's a victim, other threads have zero filled the memory by accident.
