### ISSUE TITLE
segment fault occurs built with openssl 1.1.1a

### ISSUE THREAD

**Issue by guanglinlv** [edenhill/librdkafka#2383]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

the process crash frequently caused by rdkafka library built with openssl 1.1.1a. the problem never occurs with openssl 1.0.x . 

the coredump stack:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f34f8473700 (LWP 28465)]
0x00000000006eddc5 in aesni_ecb_encrypt ()
(gdb) bt full
#0  0x00000000006eddc5 in aesni_ecb_encrypt ()
No symbol table info available.
#1  0x00000000006552e7 in aesni_ecb_cipher ()
No symbol table info available.
#2  0x0000000000661e8b in EVP_EncryptUpdate ()
No symbol table info available.
#3  0x000000000077546b in drbg_ctr_generate ()
No symbol table info available.
#4  0x000000000068a2e4 in RAND_DRBG_generate ()
No symbol table info available.
#5  0x000000000068a51a in RAND_DRBG_bytes ()
No symbol table info available.
#6  0x00000000005c7bd7 in tls1_enc ()
No symbol table info available.
#7  0x00000000005c4fc8 in do_ssl3_write ()
No symbol table info available.
#8  0x00000000005c5688 in ssl3_write_bytes ()
No symbol table info available.
#9  0x00000000005d6a66 in ssl_write_internal ()
No symbol table info available.
#10 0x00000000005d6c73 in SSL_write ()
No symbol table info available.
#11 0x00007f34fbfa8b28 in rd_kafka_transport_ssl_send (errstr_size=128, errstr=0x7f34f84725a0 "", slice=0x7f34f02b7a30, rktrans=0x3bf4630) at rdkafka_transport.c:603
        r = <optimized out>
        sum = 0
        p = 0x7f34f02b9e60
        rlen = 97
#12 rd_kafka_transport_send (rktrans=0x3bf4630, slice=slice@entry=0x7f34f02b7a30, errstr=errstr@entry=0x7f34f84725a0 "", errstr_size=errstr_size@entry=128)
    at rdkafka_transport.c:1111
No locals.
#13 0x00007f34fbf8dfd7 in rd_kafka_broker_send (slice=0x7f34f02b7a30, rkb=0x2278070) at rdkafka_broker.c:792
        r = <optimized out>
        errstr = "\000\000\000\000\000\000\000\000\371\n\000\000\000\000\000\000\350y+\360\064\177\000\000 \236+\360\064\177\000\000?\000\000\000\000\000\000\000?\000\000\000\000\000\000\000\317I", '\000' <repeats 22 times>, "Y\221\206\036\066\177\000\000\000\000\000\000\000\000\000\000\236\214\372\373\064\177\000\000\001", '\000' <repeats 30 times>
#14 rd_kafka_send (rkb=rkb@entry=0x2278070) at rdkafka_broker.c:2275
        rkbuf = 0x7f34f02b79c0
        cnt = 0
        __FUNCTION__ = "rd_kafka_send"
        __PRETTY_FUNCTION__ = "rd_kafka_send"
#15 0x00007f34fbfa7f28 in rd_kafka_transport_io_event (rktrans=0x3bf4630, events=<optimized out>) at rdkafka_transport.c:1481
        errstr = "\300y+\360\064\177\000\000@(G\370\064\177\000\000\"\000\000\000\000\000\000\000\262\265\370\373\064\177\000\000\000\000\000\000\000\000\000\000\005\003\374\373\064\177\000\000\000\000\000\000\000\000\000\000\033\v\000\000\000\000\000\000\315\060\341\000\000\000\000\000\220\236`&\000\000\000\000\340&0\002\000\000\000\000\---Type <return> to continue, or q <return> to quit---
377\377\000\000\000\000\000\000p\200'\002", '\000' <repeats 12 times>, "\377\377\003\374\064\177\000\000W\362\370\373\064\177\000\000\220)G\370\064\177\000\000p\200'\002\000\000\000\000b3\354\"l\r\000\000\000\000\000\000\000\000\000\000\317\367S?\304 \000\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377\001\000\000\000\064\177\000\000\f\340\355\"l\r\000\000\351\244"...
        r = 0
        rkb = 0x2278070
        __FUNCTION__ = "rd_kafka_transport_io_event"
#16 0x00007f34fbfa8d37 in rd_kafka_transport_io_serve (rktrans=<optimized out>, timeout_ms=<optimized out>) at rdkafka_transport.c:1515
        rkb = <optimized out>
        events = <optimized out>
#17 0x00007f34fbf9370d in rd_kafka_broker_ops_io_serve (rkb=rkb@entry=0x2278070, abs_timeout=abs_timeout@entry=14758094534116) at rdkafka_broker.c:3022
        remains_us = <optimized out>
        remains_ms = <optimized out>
#18 0x00007f34fbf94733 in rd_kafka_broker_producer_serve (abs_timeout=14758094534116, rkb=0x2278070) at rdkafka_broker.c:3513
        do_timeout_scan = 0
        next_wakeup = 14758094534116
        cnt = 66
        timeout_scan = {ri_ts_last = 14758093534286, ri_fixed = 0, ri_backoff = 0}
        initial_state = 5
#19 rd_kafka_broker_serve (rkb=rkb@entry=0x2278070, timeout_ms=<optimized out>, timeout_ms@entry=1000) at rdkafka_broker.c:4246
        __PRETTY_FUNCTION__ = "rd_kafka_broker_serve"
#20 0x00007f34fbf94c3d in rd_kafka_broker_thread_main (arg=arg@entry=0x2278070) at rdkafka_broker.c:4407
        rkb = 0x2278070
#21 0x00007f34fbfe60f7 in _thrd_wrapper_function (aArg=<optimized out>) at tinycthread.c:576
        fun = 0x7f34fbf949c0 <rd_kafka_broker_thread_main>
        arg = 0x2278070
        res = -499044
        ti = <optimized out>
#22 0x00007f361f2fedc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#23 0x00007f361e8737ad in clone () from /lib64/libc.so.6
No symbol table info available.
```

How to reproduce
================
1000+ pressure produce message.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version `1.0.0`
 - [x ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: 
```
security.protocol="SASL_SSL"
sasl.mechanisms="PLAIN"
ssl.ca.locaiton=""
ssl.certificate.location=""
ssl.key.location=""
ssl.key.password=""
sasl.username=""
sasl.password=""
statistics.interval.ms="100"
broker.version.fallback="0.10.0.0"
log.connection.close="false"
api.version.fallback.ms="100"
topic.metadata.refresh.interval.ms="90000"
compression.codec="snappy"
message.send.max.retries="3"
```
 - [x] Operating system: `Centos 7.1 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Was librdkafka built with the same openssl version as you're running with?

Can you try running the application with valgrind to get a hint of why it is crashing?
It would also be useful with debug symbols for libssl, install the openssl-debuginfo package.

**Comment by guanglinlv** [comment]
> Was librdkafka built with the same openssl version as you're running with?
yes.

> It would also be useful with debug symbols for libssl, install the openssl-debuginfo package.
i will reproduce it with debug symbols.
