### ISSUE TITLE
C++ KafkaConsumer crash in poll() - proper way to implement long-running consumer?

### ISSUE THREAD

**Issue by erkoln** [edenhill/librdkafka#2432]
Description
===========
Hello,
I wrote a consumer program some time ago, that can take a long time for processing a single message (basically using Kafka as a signalling mechanism).
The release notes for v1.0.0 of librdkafka indicate that `max.poll.interval.ms` is now enforced and `..poll()` shall be called in that interval to avoid a group rebalance that would prevent the consumer from committing its offsets later on.
I tried to `pause()` consumption and polling the consumer in a background thread during message processing before resuming, but that caused my application to crash in `consumer->poll()` (I also tried without pause() and resume() with the same results).
I might not be using the library properly, but I could not find how to do this from the documentation, so any information on how to do this properly would be very welcome.

How to reproduce
================
Change consumer loop in `examples/rdkafka_consumer_example.cpp` with:
``` C++
  while (run) {
    RdKafka::Message *msg = consumer->consume(1000);
    msg_consume(msg, NULL);
    
    consumer->pause(assignedParitions);
    volatile bool continuePolling=true;
    std::thread pollThread( [&](void) -> void {
      while( continuePolling )
        consumer->poll(500);
    });
    sleep(3);
    continuePolling = false;
    pollThread.join();
    consumer->resume(assignedParitions);
    
    delete msg;
  }
```
***NOTE:*** This code requires compiling with C++-11 enabled.

`assignedPartitions` must be populated in rebalance callback:
``` C++
    if (err == RdKafka::ERR__ASSIGN_PARTITIONS) {
      consumer->assign(partitions);
      partition_cnt = (int)partitions.size();
      assignedParitions.reserve(assignedParitions.size() + partitions.size());
      for( auto part : partitions )
        assignedParitions.push_back(
          RdKafka::TopicPartition::create(part->topic(),part->partition()) );
    } else {
      while(!assignedParitions.empty()) {
        delete assignedParitions.back();
        assignedParitions.pop_back();
      }
      consumer->unassign();
      partition_cnt = 0;
    }
```

After consuming some messages, consumer will crash due to an assertion fail in poll():
```
#> ./rdkafka_consumer_example_cpp -g g -b PLAINTEXT://127.0.0.1:9092 test
% Created consumer rdkafka#consumer-1
RebalanceCb: Local: Assign partitions: test[0], 
*** rdkafka_queue.c:488:rd_kafka_q_serve: assert: res != RD_KAFKA_OP_RES_PASS ***
Aborted (core dumped)
```

Stack trace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5f2a801 in __GI_abort () at abort.c:79
#2  0x0000555555572faa in rd_kafka_crash (file=file@entry=0x55555563feeb "rdkafka_queue.c", 
    line=line@entry=488, 
    function=function@entry=0x5555556400b0 <__FUNCTION__.28122> "rd_kafka_q_serve", 
    rk=rk@entry=0x0, reason=reason@entry=0x55555563ff40 "assert: res != RD_KAFKA_OP_RES_PASS")
    at rdkafka.c:3989
#3  0x00005555555a8ef9 in rd_kafka_q_serve (rkq=rkq@entry=0x55555589cd70, 
    timeout_ms=timeout_ms@entry=500, max_cnt=max_cnt@entry=0, 
    cb_type=cb_type@entry=RD_KAFKA_Q_CB_CALLBACK, 
    callback=callback@entry=0x555555577490 <rd_kafka_poll_cb>, opaque=opaque@entry=0x0)
    at rdkafka_queue.c:488
#4  0x00005555555a882f in rd_kafka_q_serve (rkq=0x55555589c640, timeout_ms=500, 
    max_cnt=max_cnt@entry=0, cb_type=cb_type@entry=RD_KAFKA_Q_CB_CALLBACK, 
    callback=callback@entry=0x555555577490 <rd_kafka_poll_cb>, opaque=opaque@entry=0x0)
    at rdkafka_queue.c:451
#5  0x00005555555728eb in rd_kafka_poll (rk=0x55555589b9a0, timeout_ms=<optimized out>)
    at rdkafka.c:3497
#6  0x000055555556450a in <lambda()>::operator()(void) const (__closure=0x555555899668)
    at rdkafka_consumer_example.cpp:449
#7  0x0000555555565e13 in std::__invoke_impl<void, main(int, char**)::<lambda()> >(std::__invoke_other, <lambda()> &&) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#8  0x0000555555565c18 in std::__invoke<main(int, char**)::<lambda()> >(<lambda()> &&) (__fn=...)
    at /usr/include/c++/7/bits/invoke.h:95
#9  0x00005555555660a6 in std::thread::_Invoker<std::tuple<main(int, char**)::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x555555899668) at /usr/include/c++/7/thread:234
#10 0x0000555555566062 in std::thread::_Invoker<std::tuple<main(int, char**)::<lambda()> > >::operator()(void) (this=0x555555899668) at /usr/include/c++/7/thread:243
#11 0x0000555555566032 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<main(int, char**)::<lambda()> > > >::_M_run(void) (this=0x555555899660) at /usr/include/c++/7/thread:186
#12 0x00007ffff6b6d66f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff62e26db in start_thread (arg=0x7ffff2508700) at pthread_create.c:463
#14 0x00007ffff600b88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Main thread is sleeping:
```
(gdb) thread 1
[Switching to thread 1 (Thread 0x7ffff7fc3500 (LWP 6831))]
#0  0x00007ffff5fce9d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffffffd870, 
    remaining=remaining@entry=0x7fffffffd870) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
28	../sysdeps/unix/sysv/linux/nanosleep.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5fce9d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffffffd870, 
    remaining=remaining@entry=0x7fffffffd870) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007ffff5fce8aa in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#2  0x0000555555565624 in main (argc=6, argv=0x7fffffffdb48) at rdkafka_consumer_example.cpp:451
```

Checklist
=========

 - [x] librdkafka version (release number or git tag): `v1.1.0` and `b4a3da1974655b68b80ce64acd29c441a8b2b69f` (recent master)
 - [x] Apache Kafka version: `1.0.0`
 - [x] librdkafka client configuration: `group.id=g enable.partition.eof=true`, otherwise default configuration
 - [x] Operating system: `Ubuntu 18.04.2 LTS (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by erkoln** [comment]
Hmmm, apparently I did not read the comment that said
```
   * @warning This method MUST NOT be used with the RdKafka::KafkaConsumer,
   *          use its RdKafka::KafkaConsumer::consume() instead.
   *
```
never mind -_-
