### ISSUE TITLE
Magic v0 does not support record headers

### ISSUE THREAD

**Issue by MrXianSen** [edenhill/librdkafka#2514]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
my kafka version is 2.2.1, produce data with rdkafka-1.1.0

there is some error on the broker side.  Version mismatch?

[2019-09-08 15:06:17,015] ERROR [ReplicaManager broker=4] Error processing append operation on partition zjg-10 (kafka.server.ReplicaManager)
java.lang.IllegalArgumentException: Magic v0 does not support record headers
        at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:412)
        at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:451)
        at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:604)
        at kafka.log.LogValidator$$anonfun$convertAndAssignOffsetsNonCompressed$1$$anonfun$apply$1.apply(LogValidator.scala:153)
        at kafka.log.LogValidator$$anonfun$convertAndAssignOffsetsNonCompressed$1$$anonfun$apply$1.apply(LogValidator.scala:151)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.log.LogValidator$$anonfun$convertAndAssignOffsetsNonCompressed$1.apply(LogValidator.scala:151)
        at kafka.log.LogValidator$$anonfun$convertAndAssignOffsetsNonCompressed$1.apply(LogValidator.scala:148)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.log.LogValidator$.convertAndAssignOffsetsNonCompressed(LogValidator.scala:148)
        at kafka.log.LogValidator$.validateMessagesAndAssignOffsets(LogValidator.scala:65)

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are producing with headers but your topic is configured with `message.format.version` < 0.11.0.0.

**Comment by MrXianSen** [comment]
> You are producing with headers but your topic is configured with `message.format.version` < 0.11.0.0.

done, thx
