### ISSUE TITLE
Low bandwidth causing a non-recoverable situation when kafka stops receiving messages

### ISSUE THREAD

**Issue by teoring** [edenhill/librdkafka#2710]
Description
===========
I am using librdkafka version 1.0.1
Kafka version 2.2.0
Ubuntu 16.04 ( librdkafka manually compiled )

I have two producers created within the same application and one remote Kafka service. When I am facing the low bandwidth conditions one producer stops sending the messages but the second one still producing without any issues. Even after bandwidth is restored or when I am stopping a working producer to provide some bandwidth to the first producer - recovery never happens. I have an unstable network and want to make sure that when bandwidth is low even though the queue would fill up at some point when network connectivity will recover the producer would start sending messages again.

In Kafka logs I see an error:

`[2020-02-12 16:13:06,861] WARN Attempting to send response via channel for which there is no open connection, connection id xxx:9094-yyyy:41646-93 (kafka.network.Processor)
`

`[2020-02-12 15:59:58,796] DEBUG Completed request:RequestHeader(apiKey=FETCH, apiVersion=3, clientId=consumer-1, correlationId=1585) -- {replica_id=-1,max_wait_time=500,min_bytes=1,max_bytes=52428800,topics=[{topic=events,partitions=[{partition=0,fetch_offset=5586079,partition_max_bytes=1048576}]}]},response:{throttle_time_ms=0,responses=[{topic=events,partition_responses=[{partition_header={partition=0,error_code=0,high_watermark=5586079},record_set=[]}]}]} from connection 127.0.0.1:9093-127.0.0.1:60020-5;totalTime:500.461,requestQueueTime:0.077,localTime:0.151,remoteTime:499.629,throttleTime:0.195,responseQueueTime:0.112,sendTime:0.294,securityProtocol:PLAINTEXT,principal:User:ANONYMOUS,listener:TESTA (kafka.request.logger)
[2020-02-12 15:59:58,797] DEBUG Created a new full FetchContext with 1 partition(s). Will not try to create a new session. (kafka.server.FetchManager)
[2020-02-12 15:59:58,982] DEBUG Sessionless fetch context returning 1 partition(s) (kafka.server.SessionlessFetchContext)
[2020-02-12 15:59:58,982] DEBUG Completed request:RequestHeader(apiKey=FETCH, apiVersion=3, clientId=consumer-1, correlationId=2147) -- {replica_id=-1,max_wait_time=500,min_bytes=1,max_bytes=52428800,topics=[{topic=flow-info,partitions=[{partition=0,fetch_offset=25528652,partition_max_bytes=1048576}]}]},response:{throttle_time_ms=0,responses=[{topic=flow-info,partition_responses=[{partition_header={partition=0,error_code=0,high_watermark=25528652},record_set=[]}]}]} from connection 127.0.0.1:9093-127.0.0.1:60066-5;totalTime:501.373,requestQueueTime:0.059,localTime:0.146,remoteTime:500.636,throttleTime:0.2,responseQueueTime:0.084,sendTime:0.244,securityProtocol:PLAINTEXT,principal:User:ANONYMOUS,listener:TESTA (kafka.request.logger)
[2020-02-12 15:59:58,983] DEBUG Created a new full FetchContext with 1 partition(s). Will not try to create a new session. (kafka.server.FetchManager)
**[2020-02-12 15:59:59,172] DEBUG [SocketServer brokerId=0] Connection with /XXXX disconnected (org.apache.kafka.common.network.Selector)
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:119)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:424)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:385)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:640)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:561)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:472)
        at kafka.network.Processor.poll(SocketServer.scala:830)
        at kafka.network.Processor.run(SocketServer.scala:730)
        at java.lang.Thread.run(Thread.java:748)**
[2020-02-12 15:59:59,297] DEBUG Sessionless fetch context returning 1 partition(s) (kafka.server.SessionlessFetchContext)
[2020-02-12 15:59:59,297] DEBUG Completed request:RequestHeader(apiKey=FETCH, apiVersion=3, clientId=consumer-1, correlationId=1586) -- {replica_id=-1,max_wait_time=500,min_bytes=1,max_bytes=52428800,topics=[{topic=events,partitions=[{partition=0,fetch_offset=5586079,partition_max_bytes=1048576}]}]},response:{throttle_time_ms=0,responses=[{topic=events,partition_responses=[{partition_header={partition=0,error_code=0,high_watermark=5586079},record_set=[]}]}]} from connection 127.0.0.1:9093-127.0.0.1:60020-5;totalTime:500.544,requestQueueTime:0.088,localTime:0.177,remoteTime:499.745,throttleTime:0.223,responseQueueTime:0.084,sendTime:0.224,securityProtocol:PLAINTEXT,principal:User:ANONYMOUS,listener:TESTA (kafka.request.logger)
[2020-02-12 15:59:59,298] DEBUG Created a new full FetchContext with 1 partition(s). Will not try to create a new session. (kafka.server.FetchManager)
[2020-02-12 15:59:59,484] DEBUG Sessionless fetch context returning 1 partition(s) (kafka.server.SessionlessFetchContext)`

librdkafka does not produce any errors/logs in the terminal, no error_cb ( or any other ) is subscribed.

I have tried different librdkafka settings to reduce the amount of produced throughput but still wasn't able to resolve the problem.

librdkafka settings are

```
  "compression.codec" : "gzip",
  "compression.level" : "10",
  "linger.ms" : "0.1",
  "debug" : "all",
  "topic.metadata.refresh.interval.ms" : "10000",
  "message.send.max.retries" : "1000000"
  "metadata.broker.list" : "...ip.."
```
Kafka config

```
broker.id=0
listeners=SSL://0.0.0.0:9092,TESTA://127.0.0.1:9093,TESTB://ZZZZ:9094
advertised.listeners=SSL://ZZZZ:9092,TESTA://127.0.0.1:9093,TESTB://ZZZZ:9094
listener.security.protocol.map=SSL:SSL,TESTA:PLAINTEXT,TESTB:PLAINTEXT
inter.broker.listener.name=TESTA
ssl.keystore.location=/opt/sdconsole/ssl/sd_keystore.jks
ssl.keystore.password=password
ssl.key.password=password
ssl.cipher.suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
ssl.truststore.location=keystore.jks
ssl.truststore.password=password
ssl.client.auth=required
auto.create.topics.enable=true
delete.topics.enable=true
zookeeper.connect=127.0.0.1:2181/kafka
zookeeper.connection.timeout.ms=30000
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
log.dirs=/opt/kafka-data
num.partitions=1
num.recovery.threads.per.data.dir=1
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
log.retention.hours=24
log.retention.bytes=5368709120
log.retention.check.interval.ms=300000
log.segment.bytes=1073741824
group.initial.rebalance.delay.ms=0
connections.max.idle.ms=30000

```

How to reproduce
================

1. Setup the wondeshaper limiting the bandwidth
`sudo wondershaper.sh -a <interface> -d 500 -u 500
`
2. Generate some librddkafka messages and set bandwidth to 10-20% of the throughput
~ 2.5MBps of kafka messages throughout through 500KBps channel.

Do you know why this might happen?

**Comment by teoring** [comment]
It seems the issue persists in v1.3.0. Was able to reproduce it.

**Comment by edenhill** [comment]
Suggest increasing linger.ms to increase thruput, to e.g., 50-100ms.

Also enable debugging to see what is going on: `debug=msg,queue`

**Comment by teoring** [comment]
Since I have a small bandwidth I thought I had to set linger.ms to a smaller value so the messages wouldn't be grouped and the transfer would be continuous, isn't that right?


Here is the last logs on librdkafka side:
[rdkafka.log](https://github.com/edenhill/librdkafka/files/4198527/rdkafka.log)

**Comment by edenhill** [comment]
Lower linger.ms == less messages per batch == higher overhead per message == less thruput.
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#performance

**Comment by teoring** [comment]
Here is kafka logs, I didn't find anything in particular.
[kafka.logs.log](https://github.com/edenhill/librdkafka/files/4198570/kafka.logs.log)

At some point, the local queue went full, presumably because the channel bandwidth is limited and messages are generated faster than delivered to Kafka. Is there any way to force librdkafka to retry to send the messages continuously?

**Comment by teoring** [comment]
I was trying to measure the throughput with iperf from the application using librdkafka to the Kafka server and it never went too low but the messages still at some point stopped, librdkafka reported 'queue full' and wasn't anymore reporting "PRODUCE" events. Is this a recoverable situation for librdkafka? Let's say at some point bandwidth will recover and speed will become normal.

```
[  3] local YY.YY.YY.YY port 38266 connected with XX.XX.XX.xx port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-25.3 sec   512 KBytes   166 Kbits/sec
user@demo-8:~$ iperf -c XX.XX.XX.XX
------------------------------------------------------------
Client connecting to XX.XX.XX.XX, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local YY.YY.YY.YY port 38268 connected with XX.XX.XX.XX port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-22.7 sec   512 KBytes   185 Kbits/sec
user@demo-8:~$ iperf -c XX.XX.XX.XX
------------------------------------------------------------
Client connecting to XX.XX.XX.XX, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local YY.YY.YY.YY port 38270 connected with XX.XX.XX.XX port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-25.7 sec   640 KBytes   204 Kbits/sec
user@demo-8:~$ iperf -c XX.XX.XX.XX
```

**Comment by teoring** [comment]
I can confirm that higher linger.ms and batch.num.messages along with compression - improve the overall situation. 

What I am trying to avoid now is ending up in a situation when librdkafka stops sending messages due to eventual short-term connectivity issues, even after the moment when the connection is back to normal. Can you advise on that?

**Comment by edenhill** [comment]
Reproduce this with librdkafka property `debug` set to `msg,queue,topic`  and provide the logs.

**Comment by teoring** [comment]
I have two topics - flow-info and event-logs.

Log1 is the log at the moment when flow-info has stopped to come in into the Kafka but event-logs topic was still incoming.
[log1.log](https://github.com/edenhill/librdkafka/files/4205307/log1.log)

Log2 is the moment when nothing was incoming anymore to Kafka.
[log2.log](https://github.com/edenhill/librdkafka/files/4205306/log2.log)

After logs in Log2 I am not able to recover the application to send librdkafka messages again without the restart.

**Comment by teoring** [comment]
The question I have is why flow-info topic is timeout`ed but event-logs are not. Both topics are generated by the same application, flow-info has much more messages.

`02/14/20 16:24:19]7 PRODUCE [thrd:ssl://XX.XX.XX.XX:9092/bootstrap]: ssl://XX.XX.XX.XX:9092/0: events [0]: Produce MessageSet with 2464 message(s) (51793 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
[02/14/20 16:24:19]7 TIMEOUT [thrd:ssl://XX.XX.XX.XX:9092/bootstrap]: ssl://XX.XX.XX.XX:9092/0: flow-info [0]: timed out 1+0 message(s) (MsgId 59791..59791): message.timeout.ms exceeded
[02/14/20 16:24:20]7 TIMEOUT [thrd:ssl://XX.XX.XX.XX:9092/bootstrap]: ssl://XX.XX.XX.XX:9092/0: flow-info [0]: timed out 6+0 message(s) (MsgId 59792..59797): message.timeout.ms exceeded
[02/14/20 16:24:21]7 TIMEOUT [thrd:ssl://XX.XX.XX.XX:9092/bootstrap]: ssl://XX.XX.XX.XX:9092/0: flow-info [0]: timed out 55+0 message(s) (MsgId 59798..59852): message.timeout.ms exceeded
[02/14/20 16:24:21]7 TOPPAR [thrd:ssl://XX.XX.XX.XX:9092/bootstrap]: ssl://XX.XX.XX.XX:9092/0: events [0] 18 message(s) in xmit queue (0 added from partition queue)
[02/14/20 16:24:21]7 PRODUCE [thrd:ssl://XX.XX.XX.XX:9092/bootstrap]: ssl://XX.XX.XX.XX:9092/0: events [0]: Produce MessageSet with 18 message(s) (757 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})`

**Comment by edenhill** [comment]
Sorry for dropping the ball, is this still an issue?

**Comment by teoring** [comment]
@edenhill I was able to find the root cause. Mistake in the code.
When a delivery callback is added to librdkafka, poll() needs to be called on the producer (see this [ticket](https://github.com/edenhill/librdkafka/issues/1331)).
