### ISSUE TITLE
consumer partition seemingly stuck when offset request fails

### ISSUE THREAD

**Issue by alfred-landrum** [edenhill/librdkafka#296]
With a broker running 0.8.2, and with an aggressive data retention policy that's causing log files to roll often, some partitions on my consumer get 'stuck' such that no further messages are delivered.

In the kafka broker log, I'll see something like this:

```
...
[2015-05-30 00:30:26,149] INFO Rolled new log segment for 'receiver-db1fc9b7-85b2-4016-8eda-66a356cb2ae8-35' in 1 ms. (kafka.log.Log)
[2015-05-30 00:30:26,152] WARN [KafkaApi-0] Error while responding to offset request (kafka.server.KafkaApis)
java.lang.ArrayIndexOutOfBoundsException: 7
        at kafka.server.KafkaApis.fetchOffsetsBefore(KafkaApis.scala:469)
        at kafka.server.KafkaApis.fetchOffsets(KafkaApis.scala:449)
        at kafka.server.KafkaApis$$anonfun$17.apply(KafkaApis.scala:411)
        at kafka.server.KafkaApis$$anonfun$17.apply(KafkaApis.scala:402)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at kafka.server.KafkaApis.handleOffsetRequest(KafkaApis.scala:402)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:61)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:59)
        at java.lang.Thread.run(Thread.java:745)
...
```

When the above happens, my consumer seemingly doesn't read any further data from the partition that just rolled. My current guess is that there's a kafka broker bug here related to the segment roll code racing with the offset api. I'd like to figure out why the driver stops pulling in further data from the partition.

In my setup, I've got auto.offset.reset set to 'smallest'. I'm using the rd_kafka_consume_batch_queue api, with 64 partitions per topic, feeding a single queue.  I'm not using the rdkafka offset store code; I'm tracking offsets outside of rdkafka and calling rd_kafka_consume_start_queue at program start.

**Comment by edenhill** [comment]
Interesting.
Could you reproduce this with `debug=topic` enabled?

**Comment by alfred-landrum** [comment]
will do, may take a bit to setup, as we've seen this show up on tests only after a while, am going to create some new tests that are more aggressive.

**Comment by edenhill** [comment]
Thanks, much appreciated

**Comment by alfred-landrum** [comment]
was able to repro pretty fast!  Here's debug=topic output from from the driver, filtered to show only the partition that hit the error:

```
2015-06-02T02:33:33.970Z - info: [collector-graphite] jut_node_kafka log: 7 FETCH localhost:9092/0: Fetch topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] at offset 2675433
2015-06-02T02:33:34.990Z - info: [collector-graphite] jut_node_kafka log: 7 FETCH localhost:9092/0: Fetch topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] at offset 2675433
2015-06-02T02:33:36.008Z - info: [collector-graphite] jut_node_kafka log: 7 FETCH localhost:9092/0: Fetch topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] at offset 2675964
2015-06-02T02:33:36.592Z - info: [collector-graphite] jut_node_kafka log: 7 TOPICUPD No leader change for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] with leader 0
2015-06-02T02:33:37.025Z - info: [collector-graphite] jut_node_kafka log: 7 FETCH localhost:9092/0: Fetch topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] at offset 2675964
2015-06-02T02:33:37.314Z - info: [collector-graphite] jut_node_kafka log: 7 TOPICUPD No leader change for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] with leader 0
2015-06-02T02:33:38.047Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetRequest (-2) for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]
2015-06-02T02:33:38.047Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetRequest (-1) for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]
2015-06-02T02:33:38.047Z - info: [collector-graphite] jut_node_kafka log: 7 FETCH localhost:9092/0: Fetch topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] at offset 2676521
2015-06-02T02:33:38.057Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: Offset (type 2) reply for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]: Unknown error
2015-06-02T02:33:38.057Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetReply for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]: offset 2677212: activating fetch
2015-06-02T02:33:39.277Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetRequest (0) for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]
2015-06-02T02:33:39.277Z - info: [collector-graphite] jut_node_kafka log: 7 FETCH localhost:9092/0: Skipping topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] in state offset-wait
2015-06-02T02:33:39.281Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: Offset (type 2) reply for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]: Broker: Offset out of range
2015-06-02T02:33:40.243Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetRequest (0) for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]
2015-06-02T02:33:40.243Z - info: [collector-graphite] jut_node_kafka log: 7 FETCH localhost:9092/0: Skipping topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] in state offset-wait
2015-06-02T02:33:40.246Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: Offset (type 2) reply for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]: Broker: Offset out of range
2015-06-02T02:33:41.284Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetRequest (0) for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]
2015-06-02T02:33:41.284Z - info: [collector-graphite] jut_node_kafka log: 7 FETCH localhost:9092/0: Skipping topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] in state offset-wait
2015-06-02T02:33:41.287Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: Offset (type 2) reply for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]: Broker: Offset out of range
2015-06-02T02:33:42.273Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetRequest (0) for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]
2015-06-02T02:33:42.274Z - info: [collector-graphite] jut_node_kafka log: 7 FETCH localhost:9092/0: Skipping topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] in state offset-wait
2015-06-02T02:33:42.277Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: Offset (type 2) reply for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]: Broker: Offset out of range
2015-06-02T02:33:43.299Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetRequest (-2) for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]
2015-06-02T02:33:43.299Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetRequest (-1) for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]
2015-06-02T02:33:43.299Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetRequest (0) for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]
2015-06-02T02:33:43.300Z - info: [collector-graphite] jut_node_kafka log: 7 FETCH localhost:9092/0: Skipping topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50] in state offset-wait
2015-06-02T02:33:43.309Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetReply for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]: offset 2675424: activating fetch
2015-06-02T02:33:43.309Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: OffsetReply for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]: offset 2678084: activating fetch
2015-06-02T02:33:43.309Z - info: [collector-graphite] jut_node_kafka log: 7 OFFSET localhost:9092/0: Offset (type 2) reply for topic receiver-93b40462-3850-47c1-bcda-8a3e221328ca [50]: Broker: Offset out of range
```

I'm writing down the stat output from the driver, here's the snippet for partition 50:
```
"50": { "partition":50, "leader":0, "desired":true, "unknown":false, "msgq_cnt":0, "msgq_bytes":0, "xmit_msgq_cnt":0, "xmit_msgq_bytes":0, "fetchq_cnt":5024, "fetchq_size":725124, "fetch_state":"offset-query", "query_offset":0, "next_offset":2677212, "app_offset":0, "stored_offset":-1, "commited_offset":-1, "committed_offset":-1, "eof_offset":2675964, "lo_offset":2839028, "hi_offset":2841657, "consumer_lag":164445, "txmsgs":0, "txbytes":0, "msgs": 2677212 }
```

Here's the broker log with the offset request error:
```
[2015-06-02 02:33:38,047] INFO Rolled new log segment for 'receiver-93b40462-3850-47c1-bcda-8a3e221328ca-50' in 1 ms. (kafka.log.Log)
[2015-06-02 02:33:38,049] WARN [KafkaApi-0] Error while responding to offset request (kafka.server.KafkaApis)
java.lang.ArrayIndexOutOfBoundsException: 3
        at kafka.server.KafkaApis.fetchOffsetsBefore(KafkaApis.scala:469)
        at kafka.server.KafkaApis.fetchOffsets(KafkaApis.scala:449)
        at kafka.server.KafkaApis$$anonfun$17.apply(KafkaApis.scala:411)
        at kafka.server.KafkaApis$$anonfun$17.apply(KafkaApis.scala:402)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at kafka.server.KafkaApis.handleOffsetRequest(KafkaApis.scala:402)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:61)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:59)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by alfred-landrum** [comment]
It looks like one of the offset requests used for generating consumer_lag failed, but the error handling code there doesn't currently differentiate between requests for message consumption vs. statistics gathering. The 'offset out of range' errors are occuring because rktp_query_offset is zero.

fyi, sent mail to kafka user list, was asked to file a bug for the offset request error:
https://issues.apache.org/jira/browse/KAFKA-2236

**Comment by alfred-landrum** [comment]
I'm going to try this diff and see if this fixes it:
```
diff --git a/deps/librdkafka/src/rdkafka_broker.c b/deps/librdkafka/src/rdkafka_broker.c
index 0355c2f..26fe23a 100644
--- a/deps/librdkafka/src/rdkafka_broker.c
+++ b/deps/librdkafka/src/rdkafka_broker.c
@@ -3690,12 +3690,12 @@ static void rd_kafka_toppar_offset_reply (rd_kafka_broker_t *rkb,
                        break;
                }

-               /* Backoff until next retry */
-               rktp->rktp_ts_offset_req_next = rd_clock() + 500000; /* 500ms */
-               rktp->rktp_fetch_state = RD_KAFKA_TOPPAR_FETCH_OFFSET_QUERY;
-
                 if (request->rkbuf_hndcb ==
                     (void *)rd_kafka_toppar_next_offset_handle){
+                       /* Backoff until next retry */
+                       rktp->rktp_ts_offset_req_next = rd_clock() + 500000; /* 500ms */
+                       rktp->rktp_fetch_state = RD_KAFKA_TOPPAR_FETCH_OFFSET_QUERY;
+
                         /* Signal error back to application */
                         rko = rd_kafka_op_new(RD_KAFKA_OP_ERR);
                         rko->rko_err = err;
```

**Comment by alfred-landrum** [comment]
confirmed in our environment that the fix works - closing.
