### ISSUE TITLE
Using ssl.certificate.pem does not send the full ca-chain

### ISSUE THREAD

**Issue by sunnybenari** [edenhill/librdkafka#3225]
Description
===========
When using `ssl.certificate.pem` configuration the client doesn't send the full chain. 
**Note:** `ssl.certificate.location` sends the full chain

How to reproduce
================
Run producer/consumer where `ssl.ca.location` has only the Root CA and set `ssl.certificate.pem` with the full chain. 

### Logs:

From .NET client (proxy from librdkafka) 
```
Confluent.Kafka.ProduceException`2[System.String,System.String]: Broker: Topic authorization failed
   at Confluent.Kafka.Producer`2.Produce(TopicPartition topicPartition, Message`2 message, Action`1 deliveryHandler)
   at Confluent.Kafka.Producer`2.Produce(String topic, Message`2 message, Action`1 deliveryHandler)
```

Checklist
=========
Please provide the following information:

 - [x] dot-net v1.5.3 (librdkafka - v1.5.3 )
 - [x] Apache Kafka version:  `2.6.0`
 - [x] librdkafka client configuration
 - [x] Operating system: `macOS Big sur 11.1`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue - No

**Comment by cactus620** [comment]
We met the same issue here. We're using the library of version 2.1.1. And our `ssl.certificate.pem` content is in the format like below:
```
-----BEGIN CERTIFICATE-----
(Base64-encoded certificate data for the client certificate)
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
(Base64-encoded certificate data for the intermediate CA)
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
(Base64-encoded certificate data for the root CA)
-----END CERTIFICATE-----
```

We've tried to capture the packages sent using Wireshark. Only the first block of the client certificate was sent. The intermediate CA and root CA were not sent. Please kindly help to review the issue.

**Comment by trnguyencflt** [comment]
Encounter the same issue when using `ssl.keystore.location`, only the leaf certificate is sent to server.

**Comment by abhijeet2096-confluent** [comment]
Hiting this issue in `confluent-operator`

**Comment by abhijeet2096-confluent** [comment]
This got fixed in v2.8.0 see https://github.com/confluentinc/librdkafka/releases/tag/v2.8.0

**Comment by trnguyencflt** [comment]
Yeah, it is fixed in https://github.com/confluentinc/librdkafka/pull/4894
