### ISSUE TITLE
function rd_kafka_consume_start_queue and rd_kafka_consume_stop block

### ISSUE THREAD

**Issue by nmred** [edenhill/librdkafka#352]
Hi

I want use rd_kafka_consume_start_queue and rd_kafka_consume_stop dynamic add/delete consumer topic, but it block program

code:

````
    while (1) {
        rd_kafka_message_t *rkmessage;

        /* Start consuming */
        fprintf(stderr, "%s", "start start kafka queue\n");
        for (int i = 0; i < 2; i++) {
            fprintf(stderr, "%s%d\n", "start start kafka queue ", i);
            if (rd_kafka_consume_start_queue(rkt, i, RD_KAFKA_OFFSET_STORED, queue) == -1){
                fprintf(stderr, "%% Failed to start consuming: %s\n",
                        rd_kafka_err2str(rd_kafka_errno2err(errno)));
                exit(1);
            }
        }
        fprintf(stderr, "%s", "End start kafka queue\n");

        /* Consume single message.
         * See rdkafka_performance.c for high speed
         * consuming of messages. */
        rkmessage = rd_kafka_consume_queue(queue, 100);
        if (!rkmessage) {/* timeout */
            /* Stop consuming */
            fprintf(stderr, "%s", "stop start\n");
            for (int i = 0; i < 2; i++) {
                fprintf(stderr, "%s%d\n", "debug", i);
                rd_kafka_consume_stop(rkt, i);
            }
            fprintf(stderr, "%s", "stop complete\n");
            continue;
        }

        msg_consume(rkmessage, NULL);

        /* Return message to rdkafka */
        rd_kafka_message_destroy(rkmessage);
        /* Stop consuming */
        for (int i = 0; i < 2; i++) {
            rd_kafka_consume_stop(rkt, i);
        }
    }
````

**Comment by nmred** [comment]
This continuously start & stop consumer only test can dynamic add/delete topic consumer or not

**Comment by edenhill** [comment]
There is currently a bug that prevents an application to call start+stop+start in quick succession, a bug fix is being developed and will be released shortly.
See issues #227

**Comment by nmred** [comment]
@edenhill 

I use gdb debug info:

````
(gdb) info threads
  Id   Target Id         Frame
  6    Thread 0x41711940 (LWP 20889) 0x000000356100d594 in __lll_lock_wait () from /lib64/libpthread.so.0
  5    Thread 0x42112940 (LWP 20890) 0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
  4    Thread 0x42b13940 (LWP 20891) 0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
* 3    Thread 0x43514940 (LWP 20892) 0x000000356100d594 in __lll_lock_wait () from /lib64/libpthread.so.0
  2    Thread 0x43f15940 (LWP 20893) 0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
  1    Thread 0x2b79847e4a20 (LWP 20888) rd_kafka_timer_schedule (rk=rk@entry=0x1c5e1e0,
    rtmr=rtmr@entry=0x1c60888) at rdkafka_timer.c:68
(gdb) t 4
[Switching to thread 4 (Thread 0x42b13940 (LWP 20891))]
#0  0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
(gdb) bt
#0  0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  0x00002b79842b4f62 in rd_kafka_topic_metadata_update (rkb=rkb@entry=0x1c627a0, mdt=mdt@entry=0x1c64ed1)
    at rdkafka_topic.c:1008
#2  0x00002b79842b2174 in rd_kafka_metadata_handle (rko=0x1c61ec0, size=<optimized out>, buf=<optimized out>,
    rkb=0x1c627a0) at rdkafka_broker.c:976
#3  rd_kafka_broker_metadata_reply (rkb=0x1c627a0, err=0, reply=0x1c63bb0, request=0x1c61fa0, opaque=0x1c61ec0)
    at rdkafka_broker.c:1027
#4  0x00002b79842ad196 in rd_kafka_req_response (rkbuf=0x1c63bb0, rkb=0x1c627a0) at rdkafka_broker.c:1321
#5  rd_kafka_recv (rkb=rkb@entry=0x1c627a0) at rdkafka_broker.c:1513
#6  0x00002b79842ada88 in rd_kafka_broker_io_serve (rkb=rkb@entry=0x1c627a0) at rdkafka_broker.c:2452
#7  0x00002b79842ae303 in rd_kafka_broker_consumer_serve (rkb=0x1c627a0) at rdkafka_broker.c:4105
#8  rd_kafka_broker_thread_main (arg=<optimized out>) at rdkafka_broker.c:4154
#9  0x000000356100677d in start_thread () from /lib64/libpthread.so.0
#10 0x00000035604d3c1d in clone () from /lib64/libc.so.6
#11 0x0000000000000000 in ?? ()
(gdb) i t
Ambiguous info command "t": target, tasks, terminal, threads, tp, tracepoints, tvariables, type-printers, types.
(gdb) info threads
  Id   Target Id         Frame
  6    Thread 0x41711940 (LWP 20889) 0x000000356100d594 in __lll_lock_wait () from /lib64/libpthread.so.0
  5    Thread 0x42112940 (LWP 20890) 0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
* 4    Thread 0x42b13940 (LWP 20891) 0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
  3    Thread 0x43514940 (LWP 20892) 0x000000356100d594 in __lll_lock_wait () from /lib64/libpthread.so.0
  2    Thread 0x43f15940 (LWP 20893) 0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
  1    Thread 0x2b79847e4a20 (LWP 20888) rd_kafka_timer_schedule (rk=rk@entry=0x1c5e1e0,
    rtmr=rtmr@entry=0x1c60888) at rdkafka_timer.c:68
(gdb) t 1
[Switching to thread 1 (Thread 0x2b79847e4a20 (LWP 20888))]
#0  rd_kafka_timer_schedule (rk=rk@entry=0x1c5e1e0, rtmr=rtmr@entry=0x1c60888) at rdkafka_timer.c:68
68			TAILQ_INSERT_SORTED(&rk->rk_timers, rtmr, rtmr_link,
(gdb) bt
#0  rd_kafka_timer_schedule (rk=rk@entry=0x1c5e1e0, rtmr=rtmr@entry=0x1c60888) at rdkafka_timer.c:68
#1  0x00002b79842b670f in rd_kafka_timer_schedule (rtmr=0x1c60888, rk=0x1c5e1e0) at rdkafka_timer.c:58
#2  rd_kafka_timer_start (rk=0x1c5e1e0, rtmr=0x1c60888, interval=10000,
    callback=0x2b79842b6d50 <rd_kafka_offset_file_commit_tmr_cb>, arg=0x1c606a0) at rdkafka_timer.c:114
#3  0x00002b79842b7819 in rd_kafka_offset_file_init (rktp=rktp@entry=0x1c606a0) at rdkafka_offset.c:501
#4  0x00002b79842b7f28 in rd_kafka_offset_store_init (rktp=rktp@entry=0x1c606a0) at rdkafka_offset.c:641
#5  0x00002b79842a4e9c in rd_kafka_consume_start0 (rkt=0x1c5ed30, partition=<optimized out>, offset=-1000,
    rkq=0x1c5e070) at rdkafka.c:1389
#6  0x000000000040161e in main () at /usr/home/zhongxiu/code/thread/src/queue_kafka.cpp:120
(gdb) info threads
  Id   Target Id         Frame
  6    Thread 0x41711940 (LWP 20889) 0x000000356100d594 in __lll_lock_wait () from /lib64/libpthread.so.0
  5    Thread 0x42112940 (LWP 20890) 0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
  4    Thread 0x42b13940 (LWP 20891) 0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
  3    Thread 0x43514940 (LWP 20892) 0x000000356100d594 in __lll_lock_wait () from /lib64/libpthread.so.0
  2    Thread 0x43f15940 (LWP 20893) 0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
* 1    Thread 0x2b79847e4a20 (LWP 20888) rd_kafka_timer_schedule (rk=rk@entry=0x1c5e1e0,
    rtmr=rtmr@entry=0x1c60888) at rdkafka_timer.c:68
(gdb) t 2
[Switching to thread 2 (Thread 0x43f15940 (LWP 20893))]
#0  0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
(gdb) bt
#0  0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  0x00002b79842b4f62 in rd_kafka_topic_metadata_update (rkb=rkb@entry=0x1c63560, mdt=mdt@entry=0x1c67721)
    at rdkafka_topic.c:1008
#2  0x00002b79842b2174 in rd_kafka_metadata_handle (rko=0x1c67010, size=<optimized out>, buf=<optimized out>,
    rkb=0x1c63560) at rdkafka_broker.c:976
#3  rd_kafka_broker_metadata_reply (rkb=0x1c63560, err=0, reply=0x1c61320, request=0x1c670d0, opaque=0x1c67010)
    at rdkafka_broker.c:1027
#4  0x00002b79842ad196 in rd_kafka_req_response (rkbuf=0x1c61320, rkb=0x1c63560) at rdkafka_broker.c:1321
#5  rd_kafka_recv (rkb=rkb@entry=0x1c63560) at rdkafka_broker.c:1513
#6  0x00002b79842ada88 in rd_kafka_broker_io_serve (rkb=rkb@entry=0x1c63560) at rdkafka_broker.c:2452
#7  0x00002b79842ae303 in rd_kafka_broker_consumer_serve (rkb=0x1c63560) at rdkafka_broker.c:4105
#8  rd_kafka_broker_thread_main (arg=<optimized out>) at rdkafka_broker.c:4154
#9  0x000000356100677d in start_thread () from /lib64/libpthread.so.0
#10 0x00000035604d3c1d in clone () from /lib64/libc.so.6
#11 0x0000000000000000 in ?? ()
(gdb) t 3
[Switching to thread 3 (Thread 0x43514940 (LWP 20892))]
#0  0x000000356100d594 in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x000000356100d594 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x0000003561008e8a in _L_lock_1034 () from /lib64/libpthread.so.0
#2  0x0000003561008d4c in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00002b79842b50d6 in rd_kafka_topic_leader_update (rkb=0x1c627a0, mdp=0x1c6449f, rkt=0x1c5ed30)
    at rdkafka_topic.c:674
#4  rd_kafka_topic_metadata_update (rkb=rkb@entry=0x1c62e80, mdt=mdt@entry=0x1c63f91) at rdkafka_topic.c:1032
#5  0x00002b79842b2174 in rd_kafka_metadata_handle (rko=0x1c618a0, size=<optimized out>, buf=<optimized out>,
    rkb=0x1c62e80) at rdkafka_broker.c:976
#6  rd_kafka_broker_metadata_reply (rkb=0x1c62e80, err=0, reply=0x1c61480, request=0x1c61980, opaque=0x1c618a0)
    at rdkafka_broker.c:1027
#7  0x00002b79842ad196 in rd_kafka_req_response (rkbuf=0x1c61480, rkb=0x1c62e80) at rdkafka_broker.c:1321
#8  rd_kafka_recv (rkb=rkb@entry=0x1c62e80) at rdkafka_broker.c:1513
#9  0x00002b79842ada88 in rd_kafka_broker_io_serve (rkb=rkb@entry=0x1c62e80) at rdkafka_broker.c:2452
#10 0x00002b79842ae303 in rd_kafka_broker_consumer_serve (rkb=0x1c62e80) at rdkafka_broker.c:4105
#11 rd_kafka_broker_thread_main (arg=<optimized out>) at rdkafka_broker.c:4154
#12 0x000000356100677d in start_thread () from /lib64/libpthread.so.0
#13 0x00000035604d3c1d in clone () from /lib64/libc.so.6
#14 0x0000000000000000 in ?? ()
(gdb) t 4
[Switching to thread 4 (Thread 0x42b13940 (LWP 20891))]
#0  0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
(gdb) bt
#0  0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  0x00002b79842b4f62 in rd_kafka_topic_metadata_update (rkb=rkb@entry=0x1c627a0, mdt=mdt@entry=0x1c64ed1)
    at rdkafka_topic.c:1008
#2  0x00002b79842b2174 in rd_kafka_metadata_handle (rko=0x1c61ec0, size=<optimized out>, buf=<optimized out>,
    rkb=0x1c627a0) at rdkafka_broker.c:976
#3  rd_kafka_broker_metadata_reply (rkb=0x1c627a0, err=0, reply=0x1c63bb0, request=0x1c61fa0, opaque=0x1c61ec0)
    at rdkafka_broker.c:1027
#4  0x00002b79842ad196 in rd_kafka_req_response (rkbuf=0x1c63bb0, rkb=0x1c627a0) at rdkafka_broker.c:1321
#5  rd_kafka_recv (rkb=rkb@entry=0x1c627a0) at rdkafka_broker.c:1513
#6  0x00002b79842ada88 in rd_kafka_broker_io_serve (rkb=rkb@entry=0x1c627a0) at rdkafka_broker.c:2452
#7  0x00002b79842ae303 in rd_kafka_broker_consumer_serve (rkb=0x1c627a0) at rdkafka_broker.c:4105
#8  rd_kafka_broker_thread_main (arg=<optimized out>) at rdkafka_broker.c:4154
#9  0x000000356100677d in start_thread () from /lib64/libpthread.so.0
#10 0x00000035604d3c1d in clone () from /lib64/libc.so.6
#11 0x0000000000000000 in ?? ()
(gdb) t 5
[Switching to thread 5 (Thread 0x42112940 (LWP 20890))]
#0  0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
(gdb) bt
#0  0x000000356100a530 in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  0x00002b79842b4f62 in rd_kafka_topic_metadata_update (rkb=rkb@entry=0x1c5e650, mdt=mdt@entry=0x1c661e9)
    at rdkafka_topic.c:1008
#2  0x00002b79842b2174 in rd_kafka_metadata_handle (rko=0x1c624e0, size=<optimized out>, buf=<optimized out>,
    rkb=0x1c5e650) at rdkafka_broker.c:976
#3  rd_kafka_broker_metadata_reply (rkb=0x1c5e650, err=0, reply=0x1c611c0, request=0x1c625e0, opaque=0x1c624e0)
    at rdkafka_broker.c:1027
#4  0x00002b79842ad196 in rd_kafka_req_response (rkbuf=0x1c611c0, rkb=0x1c5e650) at rdkafka_broker.c:1321
#5  rd_kafka_recv (rkb=rkb@entry=0x1c5e650) at rdkafka_broker.c:1513
#6  0x00002b79842ada88 in rd_kafka_broker_io_serve (rkb=rkb@entry=0x1c5e650) at rdkafka_broker.c:2452
#7  0x00002b79842af06d in rd_kafka_broker_ua_idle (rkb=0x1c5e650) at rdkafka_broker.c:2475
#8  rd_kafka_broker_thread_main (arg=<optimized out>) at rdkafka_broker.c:4150
#9  0x000000356100677d in start_thread () from /lib64/libpthread.so.0
#10 0x00000035604d3c1d in clone () from /lib64/libc.so.6
#11 0x0000000000000000 in ?? ()
(gdb) t 6
[Switching to thread 6 (Thread 0x41711940 (LWP 20889))]
#0  0x000000356100d594 in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x000000356100d594 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x0000003561010281 in _L_cond_lock_989 () from /lib64/libpthread.so.0
#2  0x000000356101014f in __pthread_mutex_cond_lock () from /lib64/libpthread.so.0
#3  0x000000356100b27f in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#4  0x00002b798429ee9c in pthread_cond_timedwait_ms (cond=cond@entry=0x1c5e4d0, mutex=mutex@entry=0x1c5e4a8,
    timeout_ms=<optimized out>) at rdkafka.c:109
#5  0x00002b79842b6859 in rd_kafka_timers_run (rk=rk@entry=0x1c5e1e0, timeout=timeout@entry=1000000)
    at rdkafka_timer.c:154
#6  0x00002b79842a5635 in rd_kafka_thread_main (arg=0x1c5e1e0) at rdkafka.c:1200
#7  0x000000356100677d in start_thread () from /lib64/libpthread.so.0
#8  0x00000035604d3c1d in clone () from /lib64/libc.so.6
#9  0x0000000000000000 in ?? ()
(gdb)
````

I guess dead-lock

**Comment by edenhill** [comment]
Thanks for your detailed debugging.
A fix is on the way and will be pushed to the dev branch within a couple of days, stay tuned.

**Comment by edenhill** [comment]
Fixed on master
