### ISSUE TITLE
librdkafka.dll v1.8.0 is failing to load on Windows Server 2019 x64 with no MSVC runtime v140 installed

### ISSUE THREAD

**Issue by AndrewKostousov** [edenhill/librdkafka#3557]
Description
===========
librdkafka.dll v1.8.0 is failing to load on clean Windows machine (with no MSVC runtime v140 installed). However, everything works fine on dev-machine with Visual Studio 2019 installed. 

Librdkafka v1.7.0 also works fine in both environments.

How to reproduce
================
Running the following C# program:
```
class Program
{
    static void Main()
    {
        Confluent.Kafka.Library.Load(@"c:\tmp\netcoreapp3.1\runtimes\win-x64\native\librdkafka.dll");
    }
}
```
with the following .csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="1.8.1" />
  </ItemGroup>

</Project>
```
will print the following:
```
C:\tmp\netcoreapp3.1>ConfluentKafkaRepro.exe
Unhandled exception. System.InvalidOperationException: Failed to load librdkafka at location 'c:\tmp\netcoreapp3.1\runtimes\win-x64\native\librdkafka.dll'. Win32 error: 193
   at Confluent.Kafka.Impl.Librdkafka.LoadNetStandardDelegates(String userSpecifiedPath)
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Library.Load(String path)
   at ConfluentKafka.Program.Main(String[] args) in C:\Users\andrew\source\repos\ConfluentKafkaRepro\Program.cs:line 9
```

Checklist
=========
 - [x] librdkafka version `1.8.0`
 - [x] librdkafka client configuration: `does not matter`
 - [x] Operating system: `Windows Server 2019 (x64), Version 1809, Build 17763.2183`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Critical issue

I've run (Dependencies)[https://github.com/lucasg/Dependencies] tool to look at librdkafka.dll dependencies and it complains about vcruntime140.dll:
![image](https://user-images.githubusercontent.com/857078/134327860-4398d65e-bb34-4f78-a35a-14fad6481330.png)

It seems like `runtimes\win-x64\native\vcruntime140.dll` is actually a 32-bit version of C-runtime and not a 64-bit one. Since both files `runtimes\win-x64\native\vcruntime140.dll` and `runtimes\win-x86\native\vcruntime140.dll` have the same size 76176.

**Comment by edenhill** [comment]
Yes, your analysis is spot on. We fumbled up the arch tags and provided the 32-bit version for both 32 and 64 bit builds.

A 1.8.2 update is coming soon to fix the issue.
Sorry about the inconvenience.

A workaround is to install the appropriate runtimes separately.

**Comment by UncleJosef** [comment]
18/10 versions of the library 1.8 and 1.8.1 cannot be used under win64. I spent the whole day on the solution

**Comment by edenhill** [comment]
librdkafka v1.8.2 with the required fixes was released yesterday.
