### ISSUE TITLE
Potential issues with new flush()

### ISSUE THREAD

**Issue by tmcqueen-materials** [edenhill/librdkafka#3633]
Description
===========
I want to report a potential regression in version 1.8.0+. I am the maintainer of [KafkaCrypto](https://github.com/tmcqueen-materials/kafkacrypto) and one of our users was reporting an issue where key management messages were not being produced, leading to an inability to decrypt messages. Investigation of logs revealed that the KafkaCrypto management thread was dying due to the following exception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/kafkacrypto/crypto.py", line 285, in _process_mgmt_messages
    self._kp.flush()
  File "/usr/src/app/kafkacrypto/confluent_kafka_wrapper.py", line 34, in base_callback
    self.failure(err)
AttributeError: 'FutureRecordMetadata' object has no attribute 'failure'
```
This is a highly surprising error since the definition of [FutureRecordMetadata](https://github.com/tmcqueen-materials/kafkacrypto/blob/master/kafkacrypto/confluent_kafka_wrapper.py#L22) inherits from [Future](https://github.com/dpkp/kafka-python/blob/master/kafka/future.py#L39), which defines failure, so it should not be possible for this error to occur, and yet it does.

Bisecting on released versions of confluent-kafka and librdkafka revealed the problematic behavior only occurs on librdkafka 1.8.0-1.8.2 (including latest master as of this writing), irrespective of the version of confluent-kafka.

Inspecting the changes between librdkafka 1.7.0 and 1.8.0, commit 
22707a3c082731300370443e9a96a235b1cf09b6 was identified as the source of the problem. This was further confirmed by reimplementing [flush() based on poll](https://github.com/tmcqueen-materials/kafkacrypto/commit/e3fe96b5f0fdd9e0a2a3012a729ce410f35d93e5) in KafkaCrypto, which enables it to function with all recent versions of librdkafka, including 1.8.0-1.8.2.

How to reproduce
================
Was found in a complex user environment. Appears to reliably trigger by utilizing KafkaCrypto in a consumer with a polling loop and subscribed to a topic with a large number of large messages to consume:
```
consumer = KafkaConsumer(**kafka_config)
...
consumer.subscribe(topics)

while True:
  rv = consumer.poll(timeout_ms=commit_time*1000)
  for tp,msgs in rv.items():
      ...
```
No librdkafka defaults on the producer are changed. The consumer sets these parameters:
```
enable.auto.commit : False
session.timeout.ms : 180000
heartbeat.interval.ms : 60000
message.max.bytes : 33556480
max.poll.interval.ms : 180000
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v1.8.0-v1.8.2
 - [x] Apache Kafka version: v.2.8.0
 - [x] librdkafka client configuration: see above
 - [x] Operating system: Python-3.9 on Alpine in podman container on CentOS 8.4
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by tmcqueen-materials** [comment]
I had a chance to investigate this further.  The "surprising exception" was due to an implementation bug in [kafkacrypto](https://github.com/tmcqueen-materials/kafkacrypto/commit/f18c6789e0c704e8fded68269455b9c22da384c0) . However, the hang with flush, where no messages are actually sent, persists.

I have been unable to come up with a consistent "small" reproducer, but was able to trigger it with debug=all set for the producer. That log is attached. My analysis:

1) The initial broker connection completes without incident. This is then followed by ~3 minutes of periodic wakeups -- this is time when other things are happening, and nothing has (yet) been sent with send to any topics.

2) Immediately after the first send call, librdkafka creates a new local topic.

3) Immediately after the send, but before linger.ms is exceeded, a producer flush is executed. This results in a debug line entry indicating a broker wakeup, presumably as a result of the rd_kafka_all_brokers_wakeup since there was a previous periodic wakeup only ~1 ms earlier.

4) At this point, ~0.8 seconds elapses before thrd:main queues a request for new metadata about the topic.This then repeats once a second. 

Importantly, after this, there are no messages indicating that any metadata requests are actually sent to the broker, there are no further broker wakeups, and the confluent-kafka-python flush call has not returned. This looks like the broker thread gets stuck, presumably due to some kind of livelock/deadlock . 

Unfortunately, I don't know enough about the internals of librdkafka to know whether this is happening within librdkafka, or due to some interaction with the GIL in python (since all of this is called via confluent-kafka-python). Perhaps @edenhill knows?

```
...
2021-12-30T18:30:16.863317229-05:00 stderr F %7|1640907016.863|WAKEUP|rdkafka#producer-2| [thrd:app]: ssl://kafka-broker:9093/1: Wake-up
confluent-kafka-python send is executed here at 2021-12-30T18:30:16.864012806-05:00
2021-12-30T18:30:16.864046336-05:00 stderr F %7|1640907016.864|TOPIC|rdkafka#producer-2| [thrd:app]: New local topic: topic.subs
2021-12-30T18:30:16.864055646-05:00 stderr F %7|1640907016.864|TOPPARNEW|rdkafka#producer-2| [thrd:app]: NEW topic.subs [-1] 0x7f354f2012c0 refcnt 0x7f354f201350 (at rd_kafka_topic_new0:465)
confluent-kafka-python flush is started here at 2021-12-30T18:30:16.864094207-05:00
2021-12-30T18:30:16.864111197-05:00 stderr F %7|1640907016.864|WAKEUP|rdkafka#producer-2| [thrd:app]: ssl://kafka-broker:9093/1: Wake-up
2021-12-30T18:30:17.629798467-05:00 stderr F %7|1640907017.629|NOINFO|rdkafka#producer-2| [thrd:main]: Topic topic.subs metadata information unknown
2021-12-30T18:30:17.629798467-05:00 stderr F %7|1640907017.629|NOINFO|rdkafka#producer-2| [thrd:main]: Topic topic.subs partition count is zero: should refresh metadata
2021-12-30T18:30:17.629798467-05:00 stderr F %7|1640907017.629|METADATA|rdkafka#producer-2| [thrd:main]: Requesting metadata for 1/1 topics: refresh unavailable topics
2021-12-30T18:30:17.629798467-05:00 stderr F %7|1640907017.629|METADATA|rdkafka#producer-2| [thrd:main]: ssl://kafka-broker:9093/1: Request metadata for 1 topic(s): refresh unavailable topics
2021-12-30T18:30:18.629833629-05:00 stderr F %7|1640907018.629|NOINFO|rdkafka#producer-2| [thrd:main]: Topic topic.subs metadata information unknown
2021-12-30T18:30:18.629833629-05:00 stderr F %7|1640907018.629|NOINFO|rdkafka#producer-2| [thrd:main]: Topic topic.subs partition count is zero: should refresh metadata
2021-12-30T18:30:18.629833629-05:00 stderr F %7|1640907018.629|METADATA|rdkafka#producer-2| [thrd:main]: Requesting metadata for 1/1 topics: refresh unavailable topics
2021-12-30T18:30:18.629833629-05:00 stderr F %7|1640907018.629|METADATA|rdkafka#producer-2| [thrd:main]: ssl://kafka-broker:9093/1: Request metadata for 1 topic(s): refresh unavailable topics
...
```

[full-trace-stall.log](https://github.com/edenhill/librdkafka/files/7795021/full-trace-stall.log)

**Comment by zero4573** [comment]
Hi, Sorry for reviving this, but did you ever figure this out? We're using confluent-kafka, which also uses librdkafka and running into a very similar situation where we're stuck in the 1 second loop described above.

**Comment by edenhill** [comment]
Sorry for the delay, completely missed this issue. Will look into it.

flush() will trigger callbacks, typically delivery report callbacks but also error, throttle and stats.
The flush() change did not really alter that behaviour, but made it quicker.

Is there anything in your code that has started decommissioning other parts when calling close()/flush()?

**Comment by zero4573** [comment]
Not that I know of, our code is fairly straight forward, and basically amounts to this:

```
kafka_configs = json.loads('{"bootstrap.servers":"<bootstrap_servers>","sasl.mechanism": "SCRAM-SHA-512","sasl.username": "[redacted]","sasl.password": "[redacted]","security.protocol": "SASL_SSL", "debug": "all"}')
kafka_producer = Producer(kafka_configs)

...

kafka_producer.produce(topic=KAFKA_TOPIC, value=msg)
kafka_producer.flush()
```

It also calls flush() several times when there was nothing pushed, but as its a synchronous operation, i don't believe an issue should result from that...

The one thing that may be different from @tmcqueen-materials though, is that we're running through AWS lambda.  Whats interesting, though, is that when we run this on an EC2 instance instead, the issue doesn't seem to pop up...

The relavant logs in my case:

```
%7|1649694559.279|TOPIC|rdkafka#producer-1| [thrd:app]: New local topic: service_events
%7|1649694559.299|TOPPARNEW|rdkafka#producer-1| [thrd:app]: NEW service_events [-1] 0x2943920 refcnt 0x29439b0 (at rd_kafka_topic_new0:465)
%7|1649694559.299|WAKEUP|rdkafka#producer-1| [thrd:app]: sasl_ssl://b-3.[redacted].kafka.us-east-1.amazonaws.com:9096/3: Wake-up
%7|1649694560.237|NOINFO|rdkafka#producer-1| [thrd:main]: Topic service_events metadata information unknown
%7|1649694560.237|NOINFO|rdkafka#producer-1| [thrd:main]: Topic service_events partition count is zero: should refresh metadata
%7|1649694560.238|METADATA|rdkafka#producer-1| [thrd:main]: Requesting metadata for 1/1 topics: refresh unavailable topics
%7|1649694560.238|METADATA|rdkafka#producer-1| [thrd:main]: sasl_ssl://b-3.[redacted]kafka.us-east-1.amazonaws.com:9096/3: Request metadata for 1 topic(s): refresh unavailable topics
%7|1649694561.238|NOINFO|rdkafka#producer-1| [thrd:main]: Topic service_events metadata information unknown
%7|1649694561.238|NOINFO|rdkafka#producer-1| [thrd:main]: Topic service_events partition count is zero: should refresh metadata
%7|1649694561.238|METADATA|rdkafka#producer-1| [thrd:main]: Requesting metadata for 1/1 topics: refresh unavailable topics
```

The last 4 lines repeats until the lambda timeout is hit

**Comment by conorbranagan** [comment]
Hi, I just wanted to note that we're experiencing this same issue as well. One additional data point is that when we upgraded from v1.7 to v1.8.2 on our cluster we did not experience any issues until we later moved our cluster from one running `0.10.2.1` to one running `2.7.1`.

I have some nodes handling the same workloads running `v1.8.2` of the library (blue line) and some others running `v1.7.0` (purple line) and you can see the differences in terms of errors and latencies. This is a python-based application running on VMs in GCP. 

The "write fails" graph is our code hitting the issue reported here, where it stalls on resolving metadata and the error is eventually receiving a local timeout. Both are running against a kafka cluster running `v2.7.1`.

<img width="1041" alt="Screen Shot 2022-04-18 at 9 06 19 AM" src="https://user-images.githubusercontent.com/472446/163813060-d7434e8d-8d62-4f40-85bc-49725c370bf9.png">

**Comment by tmcqueen-materials** [comment]
To answer @zero4573, no, we never figured it out because we were never able to build a "small" reproducer, and only got this on production workloads, for which our alternative python flush implementation (avoiding librdkafka's flush) resolved. We had done some stack dumps, etc, but never got far enough to figure out what was going on inside librdkafka. From Python's perspective, we always seem hung as:
```
Thread 1 (idle): "MainThread"
    0x7f578dade413 (ld-musl-x86_64.so.1)
    poll (kafkacrypto/confluent_kafka_wrapper.py:393)
    get (kafkacrypto/confluent_kafka_wrapper.py:67)
    <module> (kafka-fz-tosql.py:228)
Thread 17 (idle): "Thread-1 (_process_mgmt_messages)"
    0x7f578dade413 (ld-musl-x86_64.so.1)
    flush (kafkacrypto/confluent_kafka_wrapper.py:384)
    _process_mgmt_messages (kafkacrypto/crypto.py:291)
    run (threading.py:946)
    _bootstrap_inner (threading.py:1009)
    _bootstrap (threading.py:966)
```
Which basically means one thread is waiting for librdkafka's flush to return, and the other thread is waiting for librdkafka's poll to return [both called from the same python confluent_kafka producer object]. But just making a reproducer that had two threads trying to race to have both a flush and a poll called from the same producer object at the same time was not enough to reproduce the observed deadlock/livelock (possibly because we could not get the ordering right or it only can happen once before metadata is retrieved). We never got far enough to build librdkafka with symbols to make sense of the stack traces from the librdkafka threads.

**Comment by tmcqueen-materials** [comment]
This prompted us to test things out again. We are still able to reproducibly hit the issue with v1.8.2. However, we find that we are again (at least with light testing) unable to hit the issue in [v1.9.0-RC3](https://github.com/edenhill/librdkafka/releases/tag/v1.9.0-RC3) . So it is possible some change between v1.8.2 and v1.9.0-RC3 fixed this issue. Unfortunately we won't have time to bisect anytime soon, but perhaps that helps others.

**Comment by zero4573** [comment]
That does help, we've pivoted away form pushing directly to kafka through lambda, and instead elected to push to SQS, and have an intermediary ECS process ready/push from there so that delays aren't fatal.  Will keep an eye out for v1.9.0

**Comment by tmcqueen-materials** [comment]
@edenhill Is it possible that commit 605954111073375fae702cedf81a35a79705dcac fixed this? A git bisect with light testing fingers it as the likely commit that restores functionality.

**Comment by tmcqueen-materials** [comment]
The mystery deepens! While commit 73d9a63 seems to "often" resolve the issue, after applying the immediately following commit be4e0965796ba725244f7439cc57f76d7c5e6bc9 , I am unable to hit the issue in many trials (16 and counting). In other words, 73d9a63 and be4e096 together seem to reliably resolve the symptoms. This really suggests to me it is some kind of race/deadlock/thread coordination issue.

@edenhill Let me know if you'd like this closed (though I suspect an underlying bug is likely still present).

**Comment by edenhill** [comment]
Thank you all for the detailed troubleshoot and analysis.

I'm happy to hear that v1.9.0.. seems to fix the issue, but as @tmcqueen-materials points out it is not evident why the two bisected commits would, and that it is likely a race condition elsewhere.

What client callbacks are you setting up in the producer?
