### ISSUE TITLE
[Help Wanted]Crash on rd_segment_destroy

### ISSUE THREAD

**Issue by yueyingyehua** [edenhill/librdkafka#3675]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
My program crash with following stack:
```
(gdb) bt
#0  rd_segment_destroy (seg=0x555fca99b830) at rdbuf.c:50
#1  0x00007fcd61d5fb70 in rd_buf_destroy (rbuf=0x555fca5fdf08) at rdbuf.c:334
#2  0x00007fcd61cb0098 in rd_kafka_buf_destroy_final (rkbuf=0x555fca5fdee0) at rdkafka_buf.c:67
#3  0x00007fcd61cb16b8 in rd_kafka_buf_callback (rk=0x555fc9fac990, rkb=0x555fca4c98e0, err=RD_KAFKA_RESP_ERR_NO_ERROR, response=0x555fca601f70, request=0x555fca5fdee0) at rdkafka_buf.c:495
#4  0x00007fcd61c89671 in rd_kafka_req_response (rkbuf=0x555fca601f70, rkb=0x555fca4c98e0) at rdkafka_broker.c:1803
#5  rd_kafka_recv (rkb=rkb@entry=0x555fca4c98e0) at rdkafka_broker.c:1923
#6  0x00007fcd61caec00 in rd_kafka_transport_io_event (rktrans=rktrans@entry=0x555fca971180, events=events@entry=1) at rdkafka_transport.c:759
#7  0x00007fcd61caf883 in rd_kafka_transport_io_serve (rktrans=0x555fca971180, timeout_ms=921) at rdkafka_transport.c:818
#8  0x00007fcd61c94768 in rd_kafka_broker_ops_io_serve (rkb=rkb@entry=0x555fca4c98e0, abs_timeout=60209551017) at rdkafka_broker.c:3425
#9  0x00007fcd61c95054 in rd_kafka_broker_consumer_serve (rkb=rkb@entry=0x555fca4c98e0, abs_timeout=abs_timeout@entry=60209551017) at rdkafka_broker.c:5023
#10 0x00007fcd61c9664d in rd_kafka_broker_serve (rkb=rkb@entry=0x555fca4c98e0, timeout_ms=<optimized out>, timeout_ms@entry=1000) at rdkafka_broker.c:5166
#11 0x00007fcd61c96d95 in rd_kafka_broker_thread_main (arg=0x555fca4c98e0) at rdkafka_broker.c:5328
#12 0x00007fcd6217c12c in ?? () from /usr/lib64/libpthread.so.0
#13 0x00007fcd620b4220 in clone () from /usr/lib64/libc.so.6


(gdb) f 3
#3  0x00007fcd61cb16b8 in rd_kafka_buf_callback (rk=0x555fc9fac990, rkb=0x555fca4c98e0, err=RD_KAFKA_RESP_ERR_NO_ERROR, response=0x555fca601f70, request=0x555fca5fdee0) at rdkafka_buf.c:495
495	rdkafka_buf.c: No such file or directory.
(gdb) p request
$29 = (rd_kafka_buf_t *) 0x555fca5fdee0
(gdb) p *request
$30 = {rkbuf_link = {tqe_next = 0x0, tqe_prev = 0x555fca4c9ca0}, rkbuf_corrid = 7172, rkbuf_ts_retry = 0, rkbuf_flags = 32, rkbuf_prio = RD_KAFKA_PRIO_NORMAL, rkbuf_buf = {rbuf_segments = {tqh_first = 0x555fca99b830, 
      tqh_last = 0x555fca99b830}, rbuf_segment_cnt = 1, rbuf_wpos = 0x555fca99b830, rbuf_len = 154, rbuf_erased = 0, rbuf_size = 256, rbuf_extra = 0x555fca99b830 "11001203337896", rbuf_extra_len = 64, rbuf_extra_size = 294}, 
  rkbuf_reader = {buf = 0x555fca5fdf08, seg = 0x555fca99b830, rof = 154, start = 0, end = 154}, rkbuf_connid = 1, rkbuf_totlen = 0, rkbuf_crc = 0, rkbuf_reqhdr = {Size = 0, ApiKey = 1, ApiVersion = 11, CorrId = 0}, rkbuf_reshdr = {
    Size = 0, CorrId = 0}, rkbuf_expected_size = 0, rkbuf_replyq = {q = 0x0, version = 0}, rkbuf_orig_replyq = {q = 0x0, version = 0}, rkbuf_cb = 0x7fcd61c91220 <rd_kafka_broker_fetch_reply>, rkbuf_response = 0x0, 
  rkbuf_rkb = 0x555fca4c98e0, rkbuf_refcnt = {val = 0}, rkbuf_opaque = 0x0, rkbuf_max_retries = 2, rkbuf_retries = 0, rkbuf_features = 512, rkbuf_ts_enq = 60208630745, rkbuf_ts_sent = 500304, rkbuf_ts_timeout = 60269130745, 
  rkbuf_abs_timeout = 0, rkbuf_rel_timeout = 60500, rkbuf_force_timeout = 0 '\000', rkbuf_offset = 0, rkbuf_rktp_vers = 0x555fca62de70, rkbuf_err = RD_KAFKA_RESP_ERR_NO_ERROR, rkbuf_u = {Metadata = {topics = 0x0, reason = 0x0, 
      rko = 0x0, all_topics = 0 '\000', cgrp_update = 0 '\000', decr = 0x0, decr_lock = 0x0}, Produce = {batch = {rktp = 0x0, msgq = {rkmq_msgs = {tqh_first = 0x0, tqh_last = 0x0}, rkmq_msg_cnt = 0, rkmq_msg_bytes = 0}, pid = {
          id = 0, epoch = 0}, first_seq = 0, first_msgid = 0, epoch_base_msgid = 0, last_msgid = 0}}, EndTxn = {commit = 0 '\000'}}, rkbuf_uflow_mitigation = 0x0}

(gdb) f 1
#1  0x00007fcd61d5fb70 in rd_buf_destroy (rbuf=0x555fca5fdf08) at rdbuf.c:334
334	rdbuf.c: No such file or directory.
(gdb) p rbuf
$31 = (rd_buf_t *) 0x555fca5fdf08
(gdb) p *rbuf
$32 = {rbuf_segments = {tqh_first = 0x555fca99b830, tqh_last = 0x555fca99b830}, rbuf_segment_cnt = 1, rbuf_wpos = 0x555fca99b830, rbuf_len = 154, rbuf_erased = 0, rbuf_size = 256, rbuf_extra = 0x555fca99b830 "11001203337896", 
  rbuf_extra_len = 64, rbuf_extra_size = 294}
(gdb) p rbuf->rbuf_segments
$33 = {tqh_first = 0x555fca99b830, tqh_last = 0x555fca99b830}
(gdb) f 0
#0  rd_segment_destroy (seg=0x555fca99b830) at rdbuf.c:50
50	in rdbuf.c
(gdb) p seg
$35 = (rd_segment_t *) 0x555fca99b830
(gdb) p *seg
$36 = {seg_link = {tqe_next = 0x3330323130303131, tqe_prev = 0x1200363938373333}, seg_p = 0x50b7006449726d63 <error: Cannot access memory at address 0x50b7006449726d63>, seg_of = 7782783106049638400, seg_size = 31084746152960879, 
  seg_absof = 144164859372634115, seg_free = 0x4e436172656d6163, seg_flags = 1701080899}
```

and in my idea, I think one of the reasons for this problem is when free ptr but not set it null, so that it's caused double free
https://github.com/edenhill/librdkafka/blob/2b76b65212e5efda213961d5f84e565038036270/src/rd.h#L142-L144

How to reproduce
================
I don't know how to reproduce, it happens occasionally.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.7.0`
 - [x] Apache Kafka version: `<2.7.0>`
 - [x] librdkafka client configuration: `auto.offset.reset=latest enable.auto.commit=true fetch.message.max.bytes=102400 queued.min.messages=10000 queued.max.messages.kbytes=500000 heartbeat.interval.ms=20000 session.timeout.ms=60000 reconnect.backoff.max.ms=10000 reconnect.backoff.ms=5000 retry.backoff.ms=5000 reconnect.backoff.jitter.ms=10000 `
 - [x] Operating system: `Centos 7 x86_64>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: No logs, but has crash
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by PratRanj07** [comment]
This issue is a bit old and we don't support v1.7.0 now. I am closing this for now. If you feel, if it is still valid, please consider reopening this issue or creating a new one.
Thanks!
