### ISSUE TITLE
rd_kafka_consumer_close/rd_kafka_destroy  remain blocked indefinitely if the broker is unreachable

### ISSUE THREAD

**Issue by andreamartini** [edenhill/librdkafka#4519]
Description
===========
I'm usinng librdkafka-2.0.2, and i'm facing with rd_kafka_consumer_close(myHandle) call blocking (once the broker become unreachable).
The same problem appears with rd_kafka_destroy(myHandle). 
if i skip both api calls, a leakage appears each time a connection lost or unreachable broker happen.
Is there a way to avoid this call blocking (without running into memory leakage)?
thank you in advance

How to reproduce
================
Simulate lost connection (i,e, using clumsy)  before invoke rd_kafka_consumer_close or rd_kafka_destroy.
Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v2.0.2>`
 - [x ] Apache Kafka version: `<v2.8.2>`
 - [x] librdkafka client configuration: `<client.id="somevalue";bootstrap.servers= "my_Ip";group.id= "somevalue"; statistics.interval.ms=1000>`
 - [x] Operating system: `<Windows10>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x ] Critical issue

**Comment by jpiper** [comment]
Maybe try with the latest release of 2.3.0 first

**Comment by andreamartini** [comment]
Thank you for your answer. I get the same problem with 2.3.0 version.

**Comment by mensfeld** [comment]
@andreamartini maybe this: https://github.com/confluentinc/librdkafka/issues/4527

**Comment by davidhcefx** [comment]
Hmm, I cannot replicate your result on librdkafka version `2.2.0`.

I have tried with two approaches. The first one is to shutdown the broker completely, for example by SIGINT, and on another machine try to call `rd_kafka_destroy`. The result is that it did not get stuck.

The second approach is to send SIGSTOP to the broker. To be specific, I use `ps -Af | grep server.properties` to get the pid, and use `gdb -p <pid>` to stop the process. The result is that it also did not get stuck. However, the java Kafka broker instance would get SEGFAULT error if I stop the process for too long.

## Versions
- librdkafka: 2.2.0
- Apache kafka: 3.4.0
- OS: Debian 11

**Comment by davidhcefx** [comment]
Lately, we have also encountered this `pthread_join` deadlock issue since we upgraded from **librdkafka** v1.0 to v2.0. It did not happen frequently, only something like once in several hundreds of API calls. However, the backtrace is always similar:

```
(gdb) bt 4
#0  0x00007fb495bda4a7 in __pthread_clockjoin_ex ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fb495be57aa in thrd_join ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x0000560106309f68 in rd_kafka_destroy_app ()
#3  0x0000560106309ff4 in rd_kafka_destroy ()
(More stack frames follow...)
```

Seems like it is waiting for some thread to join, but either the target thread refused to stop or it did not exist. (blocked for over an hour)

## Version
- librdkafka: 2.2.0
- Apache kafka: 3.4.0
- OS: Debian 11

## Debugging

Some more context within Gdb:
```
(gdb) fr 3
#3  0x0000560106309ff4 in rd_kafka_destroy ()
(gdb) x/10i rd_kafka_destroy+1
   0x560106309fd8 <rd_kafka_destroy+1>: mov    rbp,rsp
   0x560106309fdb <rd_kafka_destroy+4>: sub    rsp,0x10
   0x560106309fdf <rd_kafka_destroy+8>:
    mov    QWORD PTR [rbp-0x8],rdi
   0x560106309fe3 <rd_kafka_destroy+12>:
    mov    rax,QWORD PTR [rbp-0x8]
   0x560106309fe7 <rd_kafka_destroy+16>:        mov    esi,0x0
   0x560106309fec <rd_kafka_destroy+21>:        mov    rdi,rax
   0x560106309fef <rd_kafka_destroy+24>:
    call   0x5601063099e7 <rd_kafka_destroy_app>
=> 0x560106309ff4 <rd_kafka_destroy+29>:        nop
   0x560106309ff5 <rd_kafka_destroy+30>:        leave
   0x560106309ff6 <rd_kafka_destroy+31>:        ret
(gdb) fr 2
#2  0x0000560106309f68 in rd_kafka_destroy_app ()
(gdb) x/10i rd_kafka_destroy_app+1386
   0x560106309f51 <rd_kafka_destroy_app+1386>:  add    rsp,0x10
   0x560106309f55 <rd_kafka_destroy_app+1390>:  lea    rdx,[rbp-0x14]
   0x560106309f59 <rd_kafka_destroy_app+1394>:
    mov    rax,QWORD PTR [rbp-0x10]
   0x560106309f5d <rd_kafka_destroy_app+1398>:  mov    rsi,rdx
   0x560106309f60 <rd_kafka_destroy_app+1401>:  mov    rdi,rax
   0x560106309f63 <rd_kafka_destroy_app+1404>:
    call   0x56010627a0c0 <thrd_join@plt>
=> 0x560106309f68 <rd_kafka_destroy_app+1409>:  test   eax,eax
   0x560106309f6a <rd_kafka_destroy_app+1411>:
    je     0x560106309fc3 <rd_kafka_destroy_app+1500>
   0x560106309f6c <rd_kafka_destroy_app+1413>:
    call   0x56010627a040 <__errno_location@plt>
   0x560106309f71 <rd_kafka_destroy_app+1418>:
    mov    eax,DWORD PTR [rax]
(gdb) fr 1
#1  0x00007fb495be57aa in thrd_join ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) x/10i thrd_join+8
   0x7fb495be5788 <thrd_join+8>:        mov    r8d,0x1
   0x7fb495be578e <thrd_join+14>:       sub    rsp,0x10
   0x7fb495be5792 <thrd_join+18>:       mov    rax,QWORD PTR fs:0x28
   0x7fb495be579b <thrd_join+27>:
    mov    QWORD PTR [rsp+0x8],rax
   0x7fb495be57a0 <thrd_join+32>:       xor    eax,eax
   0x7fb495be57a2 <thrd_join+34>:       mov    rsi,rsp
   0x7fb495be57a5 <thrd_join+37>:
    call   0x7fb495bda270 <__pthread_clockjoin_ex>
=> 0x7fb495be57aa <thrd_join+42>:       test   rbx,rbx
   0x7fb495be57ad <thrd_join+45>:
    je     0x7fb495be57b5 <thrd_join+53>
   0x7fb495be57af <thrd_join+47>:       mov    rdx,QWORD PTR [rsp]
(gdb) x/10i __pthread_clockjoin_ex+543
   0x7fb495bda48f <__pthread_clockjoin_ex+543>: nop
   0x7fb495bda490 <__pthread_clockjoin_ex+544>:
    call   0x7fb495be2d00 <__pthread_enable_asynccancel>
   0x7fb495bda495 <__pthread_clockjoin_ex+549>: xor    r10d,r10d
   0x7fb495bda498 <__pthread_clockjoin_ex+552>: mov    edx,r12d
   0x7fb495bda49b <__pthread_clockjoin_ex+555>: xor    esi,esi
   0x7fb495bda49d <__pthread_clockjoin_ex+557>: mov    r8d,eax
   0x7fb495bda4a0 <__pthread_clockjoin_ex+560>: mov    rdi,r13
   0x7fb495bda4a3 <__pthread_clockjoin_ex+563>: mov    eax,ebx
   0x7fb495bda4a5 <__pthread_clockjoin_ex+565>: syscall
=> 0x7fb495bda4a7 <__pthread_clockjoin_ex+567>: mov    edi,r8d
```

* I wonder if I could print the target thread ID it is waiting for, in order to check if the thread exist.
