### ISSUE TITLE
APIVERSION_QUERY timeout with older brokers

### ISSUE THREAD

**Issue by ah-** [edenhill/librdkafka#606]
Hi, forgive me if I just didn't read some documentation I should have.

I've just updated from a librdkafka build from ~April 5th to what's in master right now. When running against a 0.9 broker it now takes a minute before the client starts working.

It looks like it sends an ApiVersionRequest, which fails on the broker and then librdkafka waits an entire minute for the timeout.

Is there a good way of avoiding this timeout?

**Comment by edenhill** [comment]
I cant reproduce this.

Can you reproduce with  debug=broker,protocol  enabled?

Thanks

**Comment by ah-** [comment]
```
7|2016-04-12 07:38:52.776|rdkafka#producer-1|BRKMAIN| :0/internal: Enter main broker thread
7|2016-04-12 07:38:52.818|rdkafka#producer-1|STATE| :0/internal: Broker changed state INIT -> UP
7|2016-04-12 07:38:52.779|rdkafka#producer-1|BROKER| 127.0.0.1:9092/bootstrap: Added new broker with NodeId -1
7|2016-04-12 07:38:52.818|rdkafka#producer-1|BRKMAIN| 127.0.0.1:9092/bootstrap: Enter main broker thread
7|2016-04-12 07:38:52.818|rdkafka#producer-1|CONNECT| 127.0.0.1:9092/bootstrap: broker in state INIT connecting
7|2016-04-12 07:38:52.819|rdkafka#producer-1|CONNECT| 127.0.0.1:9092/bootstrap: Connecting to ipv4#127.0.0.1:9092 (plaintext) with socket 60
7|2016-04-12 07:38:52.819|rdkafka#producer-1|STATE| 127.0.0.1:9092/bootstrap: Broker changed state INIT -> CONNECT
rdkafka#producer-1 producing on foo2. q to exit.
7|2016-04-12 07:38:52.831|rdkafka#producer-1|CONNECT| 127.0.0.1:9092/bootstrap: Connected to ipv4#127.0.0.1:9092
7|2016-04-12 07:38:52.831|rdkafka#producer-1|CONNECTED| 127.0.0.1:9092/bootstrap: Connected
7|2016-04-12 07:38:52.831|rdkafka#producer-1|FEATURE| 127.0.0.1:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
7|2016-04-12 07:38:52.831|rdkafka#producer-1|STATE| 127.0.0.1:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
7|2016-04-12 07:38:52.842|rdkafka#producer-1|SEND| 127.0.0.1:9092/bootstrap: Sent ApiVersionRequest (v0, 25 bytes, CorrId 1)
7|2016-04-12 07:39:53.089|rdkafka#producer-1|REQERR| 127.0.0.1:9092/bootstrap: ApiVersionRequest failed: Local: Timed out: explicit actions 0x0
7|2016-04-12 07:39:53.089|rdkafka#producer-1|BROKERFAIL| 127.0.0.1:9092/bootstrap: failed: err: Local: Not implemented: (errno: Undefined error: 0)
7|2016-04-12 07:39:53.089|rdkafka#producer-1|FAIL| 127.0.0.1:9092/bootstrap: ApiVersionRequest failed: Local: Timed out: probably due to old broker version
7|2016-04-12 07:39:53.089|rdkafka#producer-1|FEATURE| 127.0.0.1:9092/bootstrap: Updated enabled protocol features -ApiVersion to 
7|2016-04-12 07:39:53.089|rdkafka#producer-1|STATE| 127.0.0.1:9092/bootstrap: Broker changed state APIVERSION_QUERY -> DOWN
7|2016-04-12 07:39:54.098|rdkafka#producer-1|CONNECT| 127.0.0.1:9092/bootstrap: broker in state DOWN connecting
7|2016-04-12 07:39:54.099|rdkafka#producer-1|CONNECT| 127.0.0.1:9092/bootstrap: Connecting to ipv4#127.0.0.1:9092 (plaintext) with socket 60
7|2016-04-12 07:39:54.099|rdkafka#producer-1|STATE| 127.0.0.1:9092/bootstrap: Broker changed state DOWN -> CONNECT
7|2016-04-12 07:39:54.110|rdkafka#producer-1|CONNECT| 127.0.0.1:9092/bootstrap: Connected to ipv4#127.0.0.1:9092
7|2016-04-12 07:39:54.110|rdkafka#producer-1|CONNECTED| 127.0.0.1:9092/bootstrap: Connected
7|2016-04-12 07:39:54.110|rdkafka#producer-1|APIVERSION| 127.0.0.1:9092/bootstrap: Using (configuration fallback) 0.9.0 protocol features
```

Broker then spits out this error:
```
[2016-04-12 07:38:52,849] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException: 17
        at org.apache.kafka.common.protocol.ApiKeys.forId(ApiKeys.java:68)
        at org.apache.kafka.common.requests.AbstractRequest.getRequest(AbstractRequest.java:39)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:79)
        at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:426)
        at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:421)
        at scala.collection.Iterator$class.foreach(Iterator.scala:742)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.network.Processor.run(SocketServer.scala:421)
        at java.lang.Thread.run(Thread.java:745)```

**Comment by edenhill** [comment]
This is what I see, a proper disconnect:
````
1460443866.446 RDKAFKA-7-CONNECT: rdkafka#producer-1: eden:9093/3: Connected to ipv4#127.0.1.1:9093
1460443866.446 RDKAFKA-7-CONNECTED: rdkafka#producer-1: eden:9093/3: Connected
1460443866.446 RDKAFKA-7-FEATURE: rdkafka#producer-1: eden:9093/3: Updated enabled protocol features +ApiVersion to ApiVersion
1460443866.446 RDKAFKA-7-STATE: rdkafka#producer-1: eden:9093/3: Broker changed state CONNECT -> APIVERSION_QUERY
1460443866.456 RDKAFKA-7-SEND: rdkafka#producer-1: eden:9093/3: Sent ApiVersionRequest (v0, 25 bytes, CorrId 1)
1460443866.466 RDKAFKA-7-BROKERFAIL: rdkafka#producer-1: eden:9093/3: failed: err: Local: Broker transport failure: (errno: Operation now in progress)
1460443866.466 RDKAFKA-7-FEATURE: rdkafka#producer-1: eden:9093/3: Updated enabled protocol features -ApiVersion to
1460443866.466 RDKAFKA-7-STATE: rdkafka#producer-1: eden:9093/3: Broker changed state APIVERSION_QUERY -> DOWN
````

**Comment by ah-** [comment]
Interesting. This is on osx with no special settings. I can try it with a broker running on linux tonight, maybe it's not closing the socket properly after the error?

**Comment by edenhill** [comment]
What exact broker version are you on?

**Comment by ah-** [comment]
```
[2016-04-11 23:17:07,440] INFO Kafka version : 0.9.0.0 (org.apache.kafka.common.utils.AppInfoParser)
[2016-04-11 23:17:07,440] INFO Kafka commitId : fc7243c2af4b2b4a (org.apache.kafka.common.utils.AppInfoParser)
```

**Comment by edenhill** [comment]
This is a regression in brokers 0.9.0.0 and 0.9.0.1, see here:
https://issues.apache.org/jira/browse/KAFKA-3547

I'll need to make a workaround in librdkafka, urghf.

What you can do is set `api.version.request=false` in librdkafka.

**Comment by edenhill** [comment]
With the workaround in place new 0.9.0 broker connections will block 10s before reconnecting and falling back to the feature set configured by `broker.version`.

Please update to latest master and give it a go.

I'm not sure what the best default value for `api.version.request` is, currently it is cleary *false* since no released broker version supports the ApiVersion, but as soon as it is released it will come into play for existing clients, so *true* is the proper long term setting.
Additionally defaults should preferably not change.

**Comment by edenhill** [comment]
Changed it to default false, for now.

**Comment by ah-** [comment]
I think kafka-python had some version detection stuff even before APIVERSION_QUERY was added. Maybe part of that logic would result in a nicer workaround?

https://github.com/dpkp/kafka-python/commit/45b2c99690fad07930d11dffb8d93dca19104c50

**Comment by edenhill** [comment]
Problem is that probing wont work with 0.9 any way due to the broker regression.

With 0.10 the probing will be history.

**Comment by ah-** [comment]
Oh and they haven't hit the issue yet because they're not probing for any features that aren't in 0.9. Argh.

**Comment by edenhill** [comment]
For reference:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by filimonov** [comment]
For googlers. If you get such a sequence of messages:
```
Broker changed state CONNECT -> APIVERSION_QUERY
Broadcasting state change
Sent ApiVersionRequest (v0, 37 bytes @ 0, CorrId 11)
failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
Updated enabled protocol features -ApiVersion to 
Broker changed state APIVERSION_QUERY -> DOWN
Broadcasting state change
Purging bufq with 1 buffers
failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
ApiVersionRequest failed: Local: Broker transport failure: probably due to old broker version (after 0ms in state DOWN)
```
That could mean you are connecting with wrong `security.protocol`, in particular, you connect to SSL enabled broker, and but SSL has not been enabled on client-side. See https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka#configure-librdkafka-client  and `security.protocol` settings in particular.

 @edenhill maybe the message https://github.com/edenhill/librdkafka/blob/4ffe54b4f59ee5ae3767f9f25dc14651a3384d62/src/rdkafka_broker.c#L2098 can give that hint?

**Comment by edenhill** [comment]
@filimonov Good idea, thanks!
