### ISSUE TITLE
if metadata request fails the client will segfault

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#632]
if metadata request fails the client will segfault in subscription process.
please improve error handling here.
this was with master branch about 1 month old but I think this has not changed.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0 0xf6c6bdab in rd_kafka_member_subscriptions_map (rkcg=0xf0a01270,
eligible_topics=0xe1bfa744, metadata=0x0, members=0xe1000e20,
member_cnt=1) at rdkafka_assignor.c:212
#1 0xf6c6c0ac in rd_kafka_assignor_run (rkcg=0xf0a01270,
protocol_name=0xe1000e68 "roundrobin", metadata=0x0, members=0xe1000e20,
member_cnt=1, errstr=0xe1bfa7fc "", errstr_size=512)
at rdkafka_assignor.c:301
#2 0xf6c618af in rd_kafka_cgrp_assignor_run (rkcg=0xf0a01270,
protocol_name=0xe1000e68 "roundrobin", metadata=0x0, members=0xe1000e20,
member_cnt=1) at rdkafka_cgrp.c:1839
#3 0xf6c61aeb in rd_kafka_cgrp_handle_Metadata (rkcg=0xf0a01270,
err=RD_KAFKA_RESP_ERR__NODE_UPDATE, md=0x0) at rdkafka_cgrp.c:1882
#4 0xf6c5bc77 in rd_kafka_assignor_handle_Metadata (rkb=0xe2c013f8,
err=RD_KAFKA_RESP_ERR__NODE_UPDATE, rkbuf=0x0, request=0xe10012f8,
opaque=0xf0a01270) at rdkafka_request.c:1768
#5 0xf6c48d7e in rd_kafka_buf_callback (rkb=0xe2c013f8,
err=RD_KAFKA_RESP_ERR__NODE_UPDATE, response=0x0, request=0xe10012f8)
at rdkafka_buf.c:472
#6 0xf6c48bf0 in rd_kafka_buf_handle_op (rko=0xe1000f00) at rdkafka_buf.c:422
#7 0xf6c60cc6 in rd_kafka_cgrp_op_serve (rkcg=0xf0a01270, rkb=0xe2c013f8)
at rdkafka_cgrp.c:1512
#8 0xf6c60f2f in rd_kafka_cgrp_serve (rkcg=0xf0a01270, rkb=0xe2c013f8)
at rdkafka_cgrp.c:1596
#9 0xf6c316c1 in rd_kafka_broker_serve (rkb=0xe2c013f8, timeout_ms=0)
at rdkafka_broker.c:2129
#10 0xf6c3801d in rd_kafka_broker_consumer_serve (rkb=0xe2c013f8)
at rdkafka_broker.c:3258
#11 0xf6c38662 in rd_kafka_broker_thread_main (arg=0xe2c013f8)
at rdkafka_broker.c:3366
#12 0xf6c6ed78 in _thrd_wrapper_function (aArg=0xe2c01998)
at tinycthread.c:599
#13 0xf7615f70 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#14 0xf6e80bee in clone () from /lib/i386-linux-gnu/libc.so.6
```

**Comment by edenhill** [comment]
Thanks for reporting this, fixed on master
