### ISSUE TITLE
Getting SIGABRT when restarting one of the brokers in the cluster

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#633]
Getting SIGABRT when restarting one of the brokers in the cluster
Master branch, checkout is about 1 month old.
```
Program terminated with signal SIGABRT, Aborted.
#0  0xf76e5ce0 in ?? ()
#1  0xf6727981 in rd_kafka_toppar_handle_Offset (rkb=0x933e3f8, 
    err=RD_KAFKA_RESP_ERR__DESTROY, rkbuf=0xe9800540, request=0xe9501248, 
    opaque=0xe95008f0) at rdkafka_request.c:221
#2  0xf6721d7e in rd_kafka_buf_callback (rkb=0x933e3f8, 
    err=RD_KAFKA_RESP_ERR__DESTROY, response=0xe9800540, request=0xe9501248)
    at rdkafka_buf.c:472
#3  0xf67058e0 in rd_kafka_req_response (rkb=0x933e3f8, rkbuf=0xe9800540)
    at rdkafka_broker.c:913
#4  0xf67062ef in rd_kafka_recv (rkb=0x933e3f8) at rdkafka_broker.c:1084
#5  0xf671f596 in rd_kafka_transport_io_event (rktrans=0xe9800468, events=1)
    at rdkafka_transport.c:1007
#6  0xf671f718 in rd_kafka_transport_io_serve (rktrans=0xe9800468, 
    timeout_ms=100) at rdkafka_transport.c:1052
#7  0xf670a7bc in rd_kafka_broker_serve (rkb=0x933e3f8, timeout_ms=0)
    at rdkafka_broker.c:2142
#8  0xf671101d in rd_kafka_broker_consumer_serve (rkb=0x933e3f8)
    at rdkafka_broker.c:3258
#9  0xf6711662 in rd_kafka_broker_thread_main (arg=0x933e3f8)
    at rdkafka_broker.c:3366
#10 0xf6747d78 in _thrd_wrapper_function (aArg=0x933bae8) at tinycthread.c:599
#11 0xf754cf70 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#12 0xf6912bee in clone () from /lib/i386-linux-gnu/libc.so.6
```
edit:
the stack unwinding seams to be strange on 64bit OS with 32bit binaries so I am not 100% sure this is the correct one

**Comment by edenhill** [comment]
Are you terminating the client at this point or is it just running as usual?

**Comment by DEvil0000** [comment]
The client gets terminated at this point.

**Comment by DEvil0000** [comment]
maybe this happened when trying to save offsets while broker is going down.
just a guess

**Comment by edenhill** [comment]
I fixed some issues with committing to down broker about a week ago.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/commit/70187dd4b3363ad24ea30146277dca2b0ff154b5

**Comment by DEvil0000** [comment]
OK, I updated to latest master and will try to reproduce.

**Comment by edenhill** [comment]
Any luck?

**Comment by DEvil0000** [comment]
Have not seen it again but I was quite busy doing other stuff so I am not sure if it is fixed.
I will close it and reopen if this reappears.
