### ISSUE TITLE
rd_kafka_cgrp_partitions_fetch_start assertion error

### ISSUE THREAD

**Issue by Pchelolo** [edenhill/librdkafka#761]
Description
===========

When I'm creating and subscribing a lot of consumer processes with the same consumer group, sometimes it aborts with `*** ../deps/librdkafka/src/rdkafka_cgrp.c:790:rd_kafka_cgrp_partitions_fetch_start: assert: rkcg->rkcg_assigned_cnt <= (rkcg->rkcg_assignment ? rkcg->rkcg_assignment->cnt : 0) ***`

How to reproduce
================

There's no particular way to reproduce this, it just happens sometimes (around 1 out of 10 processes abort like that). I'm using [node-rdkafka](https://github.com/Blizzard/node-rdkafka) wrapper for node.js, so it might be related to it. 

I mostly ask for help on how to debug this further to identify the reason of this.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): master
 - [x] Apache Kafka version: 0.9.0.1
 - [x] librdkafka client configuration: defaults
 - [x] Operating system: debian jessie
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
It logged `Group "change-prop-mw_purge": starting fetchers for 0 assigned partition(s) in join-state assigned (usable_offsets=no)` right before asserting
 - [x] Provide broker log excerpts: nothing unusual
 - [ ] Critical issue

**Comment by edenhill** [comment]
Do you have a core file (might require `ulimit -c unlimited`) which you can extract a backtrace from (`bt` in gdb)?

**Comment by Pchelolo** [comment]
@edenhill Here's it:
```
#0  0x00007fbe79bc1067 in raise () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007fbe79bc2448 in abort () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007fbe7410d794 in rd_kafka_crash (file=file@entry=0x7fbe74162998 "../deps/librdkafka/src/rdkafka_cgrp.c", line=line@entry=790, 
    function=function@entry=0x7fbe74163660 <__FUNCTION__.20626> "rd_kafka_cgrp_partitions_fetch_start", rk=rk@entry=0x0, 
    reason=reason@entry=0x7fbe74162ac0 "assert: rkcg->rkcg_assigned_cnt <= (rkcg->rkcg_assignment ? rkcg->rkcg_assignment->cnt : 0)") at ../deps/librdkafka/src/rdkafka.c:2379
No locals.
#3  0x00007fbe741408a9 in rd_kafka_cgrp_partitions_fetch_start (rkcg=0x7fbe600057e0, assignment=0x7fbe1c014370, usable_offsets=<optimized out>) at ../deps/librdkafka/src/rdkafka_cgrp.c:789
        i = <optimized out>
        usable_offsets = <optimized out>
        assignment = 0x7fbe1c014370
        rkcg = 0x7fbe600057e0
#4  0x00007fbe74140af0 in rd_kafka_cgrp_offsets_fetch_response (rk=0x7fbe600052c0, rkb=0x7fbe60006cd0, err=RD_KAFKA_RESP_ERR_NO_ERROR, reply=0x7fbe20222c60, request=0x7fbe1c023ad0, opaque=0x7fbe1c014370)
    at ../deps/librdkafka/src/rdkafka_cgrp.c:674
        offsets = 0x7fbe1c014370
        rkcg = 0x7fbe600057e0
#5  0x00007fbe7412c484 in rd_kafka_buf_callback (rk=0x7fbe600052c0, rkb=0x7fbe60006cd0, err=RD_KAFKA_RESP_ERR_NO_ERROR, response=0x7fbe20222c60, request=0x7fbe1c023ad0)
    at ../deps/librdkafka/src/rdkafka_buf.c:515
        __FUNCTION__ = "rd_kafka_buf_callback"
#6  0x00007fbe74146b54 in rd_kafka_cgrp_op_serve (rkb=0x7fbe60006cd0, rkcg=0x7fbe600057e0) at ../deps/librdkafka/src/rdkafka_cgrp.c:1664
        rktp = 0x0
        err = <optimized out>
        silent_op = <optimized out>
        rko = 0x7fbe202209d0
#7  rd_kafka_cgrp_serve (rkcg=0x7fbe600057e0) at ../deps/librdkafka/src/rdkafka_cgrp.c:1746
        rkb = 0x7fbe60006cd0
        rkb_state = 4
#8  0x00007fbe7410e6f3 in rd_kafka_thread_main (arg=arg@entry=0x7fbe600052c0) at ../deps/librdkafka/src/rdkafka.c:974
        sleeptime = <optimized out>
        rk = 0x7fbe600052c0
        tmr_topic_scan = {rtmr_link = {tqe_next = 0x7fbe09ff2e90, tqe_prev = 0x7fbe60005750}, rtmr_next = 1807334889764, rtmr_interval = 1000000, 
          rtmr_callback = 0x7fbe74106f10 <rd_kafka_topic_scan_tmr_cb>, rtmr_arg = 0x0}
        tmr_stats_emit = {rtmr_link = {tqe_next = 0x0, tqe_prev = 0x0}, rtmr_next = 0, rtmr_interval = 0, rtmr_callback = 0x7fbe74108940 <rd_kafka_stats_emit_tmr_cb>, rtmr_arg = 0x0}
        tmr_metadata_refresh = {rtmr_link = {tqe_next = 0x0, tqe_prev = 0x7fbe09ff2e30}, rtmr_next = 1807526846128, rtmr_interval = 300000000, 
          rtmr_callback = 0x7fbe74107160 <rd_kafka_metadata_refresh_cb>, rtmr_arg = 0x0}
#9  0x00007fbe74154688 in _thrd_wrapper_function (aArg=<optimized out>) at ../deps/librdkafka/src/tinycthread.c:611
        fun = 0x7fbe7410e560 <rd_kafka_thread_main>
        arg = 0x7fbe600052c0
        res = 0
        ti = <optimized out>
#10 0x00007fbe7d24c0a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
```

**Comment by edenhill** [comment]
Thank you, I've managed to reproduce this, a fix is on the way.
