### ISSUE TITLE
Double free when using "topic.blacklist" setting.

### ISSUE THREAD

**Issue by siffiejoe** [edenhill/librdkafka#778]
Description
===========

Setting the configuration key "topic.blacklist" and later calling `consumer->close()` leads to a double free or corruption:
```
Using rdkafka 0.9.1
*** Error in `../../amd64/bin/bugreport_dbg': double free or corruption (fasttop): 0x0000000001509aa0 ***
Aborted
```

GDB says:
```
Using rdkafka 0.9.1
[New Thread 0x7ffff610f700 (LWP 27658)]
[New Thread 0x7ffff590e700 (LWP 27659)]
[New Thread 0x7ffff510d700 (LWP 27660)]
[New Thread 0x7fffeffff700 (LWP 27661)]
[Thread 0x7fffeffff700 (LWP 27661) exited]
[Thread 0x7ffff590e700 (LWP 27659) exited]
*** Error in `../../amd64/bin/bugreport_dbg': double free or corruption (fasttop): 0x0000000000603aa0 ***
[Thread 0x7ffff510d700 (LWP 27660) exited]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff610f700 (LWP 27658)]
0x00007ffff6dafc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6dafc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6db3028 in __GI_abort () at abort.c:89
#2  0x00007ffff6dec2a4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff6efa6b0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6df855e in malloc_printerr (ptr=<optimized out>, str=0x7ffff6efa878 "double free or corruption (fasttop)", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007ffff799a12d in rd_free (ptr=<optimized out>) at rd.h:99
#6  rd_kafka_pattern_destroy (plist=<optimized out>, rkpat=0x6039c0) at rdkafka_pattern.c:38
#7  0x00007ffff799a1c8 in rd_kafka_pattern_list_clear (plist=0x6048f0) at rdkafka_pattern.c:177
#8  0x00007ffff797f82d in rd_kafka_anyconf_clear (prop=<optimized out>, conf=<optimized out>) at rdkafka_conf.c:1200
#9  rd_kafka_anyconf_destroy (scope=1, conf=0x604830) at rdkafka_conf.c:1232
#10 0x00007ffff796dd33 in rd_kafka_destroy_final (rk=0x604620) at rdkafka.c:475
#11 0x00007ffff796e041 in rd_kafka_thread_main (arg=<optimized out>) at rdkafka.c:991
#12 0x00007ffff79a379f in _thrd_wrapper_function (aArg=<optimized out>) at tinycthread.c:611
#13 0x00007ffff6b63184 in start_thread (arg=0x7ffff610f700) at pthread_create.c:312
#14 0x00007ffff6e7337d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) 
```
and Valgrind says (before I kill it):
```
==27696== Memcheck, a memory error detector
==27696== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==27696== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==27696== Command: ../../amd64/bin/bugreport_dbg
==27696== Parent PID: 27532
==27696== 
==27696== Thread 2:
==27696== Invalid write of size 8
==27696==    at 0x508C11C: rd_kafka_pattern_destroy (rdkafka_pattern.c:34)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02810 is 192 bytes inside a block of size 456 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x505F475: rd_free (rd.h:99)
==27696==    by 0x505F475: rd_kafka_new (rdkafka.c:1053)
==27696==    by 0x4E47BA1: RdKafka::KafkaConsumer::create(RdKafka::Conf*, std::string&) (KafkaConsumerImpl.cpp:63)
==27696==    by 0x4016F6: main (bugreport.cpp:34)
==27696== 
==27696== Invalid read of size 8
==27696==    at 0x508C100: rd_kafka_pattern_destroy (rdkafka_pattern.c:34)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b60 is 0 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid read of size 8
==27696==    at 0x508C140: rd_kafka_pattern_destroy (rdkafka_pattern.c:34)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b68 is 8 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid read of size 8
==27696==    at 0x508C114: rd_kafka_pattern_destroy (rdkafka_pattern.c:34)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b68 is 8 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid read of size 8
==27696==    at 0x5BB6A14: regfree (regcomp.c:646)
==27696==    by 0x508C123: rd_kafka_pattern_destroy (rdkafka_pattern.c:36)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b70 is 16 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid read of size 8
==27696==    at 0x5BB6A21: regfree (regcomp.c:652)
==27696==    by 0x508C123: rd_kafka_pattern_destroy (rdkafka_pattern.c:36)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b90 is 48 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid write of size 8
==27696==    at 0x5BB6A25: regfree (regcomp.c:649)
==27696==    by 0x508C123: rd_kafka_pattern_destroy (rdkafka_pattern.c:36)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b70 is 16 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid write of size 8
==27696==    at 0x5BB6A2C: regfree (regcomp.c:650)
==27696==    by 0x508C123: rd_kafka_pattern_destroy (rdkafka_pattern.c:36)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b78 is 24 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid read of size 8
==27696==    at 0x5BB6A39: regfree (regcomp.c:655)
==27696==    by 0x508C123: rd_kafka_pattern_destroy (rdkafka_pattern.c:36)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b98 is 56 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid write of size 8
==27696==    at 0x5BB6A3D: regfree (regcomp.c:653)
==27696==    by 0x508C123: rd_kafka_pattern_destroy (rdkafka_pattern.c:36)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b90 is 48 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid write of size 8
==27696==    at 0x5BB6A4A: regfree (regcomp.c:656)
==27696==    by 0x508C123: rd_kafka_pattern_destroy (rdkafka_pattern.c:36)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b98 is 56 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid read of size 8
==27696==    at 0x508C124: rd_free (rd.h:99)
==27696==    by 0x508C124: rd_kafka_pattern_destroy (rdkafka_pattern.c:38)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02bb0 is 80 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid free() / delete / delete[] / realloc()
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C12C: rd_free (rd.h:99)
==27696==    by 0x508C12C: rd_kafka_pattern_destroy (rdkafka_pattern.c:38)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b039a0 is 0 bytes inside a block of size 5 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C12C: rd_free (rd.h:99)
==27696==    by 0x508C12C: rd_kafka_pattern_destroy (rdkafka_pattern.c:38)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== Invalid free() / delete / delete[] / realloc()
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696==  Address 0x6b02b60 is 0 bytes inside a block of size 88 free'd
==27696==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27696==    by 0x508C1C7: rd_kafka_pattern_list_clear (rdkafka_pattern.c:177)
==27696==    by 0x507182C: rd_kafka_anyconf_clear (rdkafka_conf.c:1200)
==27696==    by 0x507182C: rd_kafka_anyconf_destroy (rdkafka_conf.c:1232)
==27696==    by 0x505FD32: rd_kafka_destroy_final (rdkafka.c:475)
==27696==    by 0x5060040: rd_kafka_thread_main (rdkafka.c:991)
==27696==    by 0x509579E: _thrd_wrapper_function (tinycthread.c:611)
==27696==    by 0x5EA0183: start_thread (pthread_create.c:312)
==27696==    by 0x5BCD37C: clone (clone.S:111)
==27696== 
==27696== 
==27696== More than 10000000 total errors detected.  I'm not reporting any more.
==27696== Final error counts will be inaccurate.  Go fix your program!
==27696== Rerun with --error-limit=no to disable this cutoff.  Note
==27696== that errors may occur in your program without prior warning from
==27696== Valgrind, because errors are no longer being displayed.
==27696== 
```

How to reproduce
================

```cpp
#include <string>
#include <iostream>
#include <stdexcept>

#include <librdkafka/rdkafkacpp.h>


/**
 * RdKafka configuration (global/topic), but throwing exceptions in
 * case of an error instead of using a return value.
 */
template <typename T>
void setConf(RdKafka::Conf& conf, std::string const& name, T const& value)
{
    std::string errmsg;
    RdKafka::Conf::ConfResult res = conf.set(name, value, errmsg);
    if (res != RdKafka::Conf::CONF_OK)
        throw std::runtime_error("Configuration error ('" + name + "'): " + errmsg);
}


int main(int argc, char** argv)
{
    std::cout << "Using rdkafka " << RdKafka::version_str() << std::endl;
    try
    {
        RdKafka::Conf* config = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
        setConf(*config, "metadata.broker.list", "localhost");
        setConf(*config, "group.id", "xyz");
#if 1
        setConf(*config, "topic.blacklist", "__.*");
#endif
        std::string errmsg;
        RdKafka::KafkaConsumer* consumer = RdKafka::KafkaConsumer::create(config, errmsg);
        if (!consumer)
        {
            std::cerr << "Error creating KafkaConsumer object: " << errmsg << std::endl;
            return 1;
        }
#if 1
        consumer->close();
#endif
        delete consumer;
        delete config;
    }
    catch (std::exception const& e)
    {
        std::cerr << "[ERROR] " << e.what() << std::endl;
        return 1;
    }
    std::cout << "Cleaning up ..." << std::endl;
    RdKafka::wait_destroyed(5000);
    return 0;
}
```
running together with the default
```
$ bin/zookeeper-server-start.sh config/zookeeper.properties
```
and
```
$ bin/kafka-server-start.sh config/server.properties
```
from the Kafka tarball.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.1
 - [x] Apache Kafka version: 0.10.0.0
 - [ ] librdkafka client configuration:
 - [x] Operating system: Linux un1060x 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks for your detailed bug report.

The issue is now fixed on master.
