### ISSUE TITLE
broker reconnect will go into endless loop as the timeout_ms is zero

### ISSUE THREAD

**Issue by Benjaad** [edenhill/librdkafka#779]
## Description
===========
```
case RD_KAFKA_BROKER_STATE_DOWN:
                        /* Throttle & jitter reconnects to avoid
                         * thundering horde of reconnecting clients after
                         * a broker / network outage. Issue #403 */
                        if (rkb->rkb_rk->rk_conf.reconnect_jitter_ms &&
                            rkb->rkb_ts_connect &&
                            (backoff = rd_clock() - (
                                    rkb->rkb_ts_connect +
                                    (rd_jitter((int)(rkb->rkb_rk->rk_conf.
						     reconnect_jitter_ms*0.5),
                                               (int)(rkb->rkb_rk->rk_conf.
						     reconnect_jitter_ms*1.5))
                                     * 1000))) < 0) {
                                rd_rkb_dbg(rkb, BROKER, "RECONNECT",
                                           "Delaying next reconnect by %dms",
                                           -(int)(backoff/1000));
                                rd_kafka_broker_ua_idle(rkb,
							(int)(-backoff / 1000) );
                                rkb->rkb_ts_connect = 0;
                                continue;
                        }
			if (rd_kafka_broker_connect(rkb) == -1) {
			}
			break;
```

in this case,  if backoff is less than 1000,  (-backoff / 1000) will be zero.  rd_kafka_broker_ua_idle will not return as the conditions in while is always be true.

```
static void rd_kafka_broker_ua_idle (rd_kafka_broker_t *rkb, int timeout_ms)
 {
	int initial_state = rkb->rkb_state;
        rd_ts_t ts_end = timeout_ms ? rd_clock() + timeout_ms * 1000 : 0;
	while (!rd_kafka_broker_terminating(rkb) &&
	       (int)rkb->rkb_state == initial_state &&
               (!ts_end || ts_end > rd_clock())) {

                rd_kafka_broker_toppars_serve(rkb);

		rd_kafka_broker_serve(rkb, 10);
        }
}
```

The stack information
```
#0  0x00007f096f33ba5e in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f09709b3597 in cnd_timedwait_ms (cnd=0x151f018, mtx=0x151eff0, timeout_ms=<value optimized out>) at tinycthread.c:498
        ret = <value optimized out>
        tv = {tv_sec = 1473212386, tv_usec = 753358}
        ts = {tv_sec = 1473212386, tv_nsec = 763358000}
#2  0x00007f097099522a in rd_kafka_q_pop (rkq=0x151eff0, timeout_ms=10, version=<value optimized out>) at rdkafka_queue.c:276
        rko = 0x0
#3  0x00007f0970986e78 in rd_kafka_broker_serve (rkb=0x151efb0, timeout_ms=10) at rdkafka_broker.c:3034
        rko = <value optimized out>
        now = 10
#4  0x00007f09709871f1 in rd_kafka_broker_ua_idle (rkb=0x151efb0, timeout_ms=<value optimized out>) at rdkafka_broker.c:3095
        initial_state = 1
        ts_end = 0
#5  0x00007f09709888cb in rd_kafka_broker_thread_main (arg=0x151efb0) at rdkafka_broker.c:4361
        backoff = -10
        rkb = 0x151efb0
        rk = 0x151dde0
#6  0x00007f09709b34ef in _thrd_wrapper_function (aArg=<value optimized out>) at tinycthread.c:611
        fun = 0x7f0970987fe0 <rd_kafka_broker_thread_main>
        arg = 0x151efb0
        res = -516
        ti = <value optimized out>
#7  0x00007f096f337aa1 in start_thread () from /lib64/libpthread.so
```

## How to reproduce
================
it is Very difficult to reproduce.

## Temporary Solution;
```
                        (backoff = rd_clock() - (
                                    rkb->rkb_ts_connect +
                                    (rd_jitter((int)(rkb->rkb_rk->rk_conf.
						     reconnect_jitter_ms*0.5),
                                               (int)(rkb->rkb_rk->rk_conf.
						     reconnect_jitter_ms*1.5))
                                     * 1000))) < 0) {
        rd_kafka_broker_ua_idle(rkb,
							(int)(-backoff / 1000));
```
backoff use millisecond for unit, change as follow

```
                        (backoff = rd_clock()/1000 - (
                                    rkb->rkb_ts_connect/1000 +
                                    (rd_jitter((int)(rkb->rkb_rk->rk_conf.
						     reconnect_jitter_ms*0.5),
                                               (int)(rkb->rkb_rk->rk_conf.
						     reconnect_jitter_ms*1.5))
                                         ))) < 0) {
                              rd_kafka_broker_ua_idle(rkb,
							(int)(-backoff));
```
is it all right?

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [x] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks for a great bug report!
Issue is fixed on master now
