### ISSUE TITLE
Deadlock on failed partitioning

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#797]
# Description

```
(gdb) thread 1
[Switching to thread 1 (Thread 0x7f54aaa6f780 (LWP 12921))]
#0  pthread_rwlock_wrlock () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_wrlock.S:85
85      in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_wrlock.S
(gdb) backtrace
#0  pthread_rwlock_wrlock () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_wrlock.S:85
#1  0x00007f54a721c443 in rd_kafka_topic_destroy (app_rkt=0x15b1610) at rdkafka_topic.c:82
#2  0x00007f54a721acbb in rd_kafka_msg_destroy (rk=<optimized out>, rkm=rkm@entry=0x9dae3b0) at rdkafka_msg.c:51
#3  0x00007f54a721b6eb in rd_kafka_msg_new (rkt=0x15b1610, force_partition=-1, msgflags=2, payload=0x3a66fe8 "@84d34dfc18eac0b0ec81af2eb49339f1\030\067\060.24.17.244\266\257\320\375\n\266\257\320\375\n\b\004\240\v\300\a", len=105, key=0x52e73b8, keylen=32, msg_opaque=0x0)
    at rdkafka_msg.c:234
#4  0x00007f54a78ec60c in RdKafka::ProducerImpl::produce (this=<optimized out>, topic=<optimized out>, partition=-1, msgflags=2, payload=0x3a66fe8, len=105, key=0x39ceec8, msg_opaque=0x0) at ProducerImpl.cpp:102
```

Other relevant thread is in topic scanner, so most likely a lock-ordering issue:

```
gdb) thread 7
[Switching to thread 7 (Thread 0x7f54a14cf700 (LWP 13053))]
#0  pthread_rwlock_wrlock () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_wrlock.S:85
85      ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_wrlock.S: No such file or directory.
(gdb) backtrace
#0  pthread_rwlock_wrlock () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_wrlock.S:85
#1  0x00007f54a721d8e1 in rd_kafka_topic_scan_all (rk=rk@entry=0x15aea70, now=27418596152) at rdkafka_topic.c:858
#2  0x00007f54a7200ae6 in rd_kafka_topic_scan_tmr_cb (rkts=<optimized out>, arg=<optimized out>) at rdkafka.c:912
#3  0x00007f54a721fb18 in rd_kafka_timers_run (rkts=rkts@entry=0x15aeeb8, timeout_us=timeout_us@entry=0) at rdkafka_timer.c:226
#4  0x00007f54a7207c2f in rd_kafka_thread_main (arg=arg@entry=0x15aea70) at rdkafka.c:998
#5  0x00007f54a724aed7 in _thrd_wrapper_function (aArg=<optimized out>) at tinycthread.c:613
#6  0x00007f54aa454184 in start_thread (arg=0x7f54a14cf700) at pthread_create.c:312
#7  0x00007f54a950537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by edenhill** [comment]
Havent been able to reproduce this. Will not make 0.9.2

**Comment by edenhill** [comment]
not reproducible, lots of changes since then.
