### ISSUE TITLE
The java keystore generated by gen-ssl-certs.sh seems not to be working

### ISSUE THREAD

**Issue by ciasom** [edenhill/librdkafka#823]
Description
===========
I can't make kafka-console-producer.sh work with the java keystore generated by gen-ssl-certs.sh.

How to reproduce
================
(1)Followed the steps in https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka.  The librdkafka++ client can successfully connect to server via SSL. 

(2)Change producer.properties
bootstrap.servers=localhost:9093
ssl.truststore.location=/usr/local/kafka/ssl/kafka_client.truststore.jks
ssl.truststore.password=abcdefgh
ssl.keystore.location=/usr/local/kafka/ssl/kafka_client.keystore.jks
ssl.keystore.password=abcdefgh
ssl.key.password=abcdefgh
security.protocol=SSL
ssl.enabled.protocols=TLSv1.2,TLSv1.1,TLSv1
ssl.keystore.type=JKS
ssl.truststore.type=JKS

(3)run kafka-console-producer.sh
./bin/kafka-console-producer.sh --topic test --broker-list localhost:9093 --producer.config ./config/producer.properties

(4)Type in anything then press Enter, get this:
WARN Failed to send SSL Close message  (org.apache.kafka.common.network.SslTransportLayer)
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.kafka.common.network.SslTransportLayer.flush(SslTransportLayer.java:195)
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:150)
	at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:690)
	at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:47)
	at org.apache.kafka.common.network.Selector.close(Selector.java:471)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:348)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:283)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:260)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:229)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:134)
	at java.lang.Thread.run(Thread.java:745)
(5)After checking the steps here: http://www.confluent.io/blog/apache-kafka-security-authorization-authentication-encryption/, I remove the generated client truststore and keystore files and re-generate by running the following commands:
keytool -keystore kafka_client.truststore.jks -alias CARoot -import -file ca-cert
keytool -keystore kafka_client.keystore.jks -alias localhost -validity 10000 -genkey
keytool -keystore kafka_client.keystore.jks -alias localhost -certreq -file cert-file
openssl x509 -req -CA ca-cert -CAkey ca-cert.key -in cert-file -out cert-signed -days 10000 -CAcreateserial
keytool -keystore kafka_client.keystore.jks -alias CARoot -import -file ca-cert
keytool -keystore kafka_client.keystore.jks -alias localhost -import -file cert-signed

Now kafka-console-producer.sh is working.  So it looks some steps are missing in gen-ssl-certs.sh for generating java keystore.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): librdkafka-debian-0.9.1-1
 - [ ] Apache Kafka version: kafka_2.11-0.10.0.1
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64 GNU/Linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks for your report and analysis.

Would you mind filing a PR to fix the issue?

**Comment by ciasom** [comment]
Pull request created.  Hope I didn't do wrong thing.
