### ISSUE TITLE
No such configuration property: "broker.version.fallback" on pykafka 2.5.0

### ISSUE THREAD

**Issue by ummae** [edenhill/librdkafka#902]
Description
===========
After upgrade to 2.5.0 from 2.3.1 using pip, I got following error with `use_rdkafka=True`
```
2016-11-14 11:24:06,290 : DEBUG : Configuring _rdk_consumer...
[('client.id', 'pykafka.rdkafka'), ('broker.version.fallback', '0.9.0'), ('queued.max.messages.kbytes', '2048000'), ('receive.message.max.bytes', '22020096'), ('queued.min.messages', '2000'), ('fetch.message.max.bytes', '1048576'), ('fetch.wait.max.ms', '100'), ('fetch.min.bytes', '1'), ('socket.timeout.ms', '30000')] [('auto.commit.enable', 'false'), ('auto.offset.reset', 'smallest')]
2016-11-14 11:24:06,290 : ERROR : Stopping consumer in response to error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/pykafka/balancedconsumer.py", line 306, in start
    self._rebalance()
  File "/usr/lib64/python2.7/site-packages/pykafka/balancedconsumer.py", line 603, in _rebalance
    self._update_member_assignment()
  File "/usr/lib64/python2.7/site-packages/pykafka/balancedconsumer.py", line 578, in _update_member_assignment
    if self._setup_internal_consumer(new_partitions):
  File "/usr/lib64/python2.7/site-packages/pykafka/balancedconsumer.py", line 359, in _setup_internal_consumer
    cns = self._get_internal_consumer(partitions=list(partitions), start=start)
  File "/usr/lib64/python2.7/site-packages/pykafka/balancedconsumer.py", line 417, in _get_internal_consumer
    consumer_id=self._consumer_id
  File "/usr/lib64/python2.7/site-packages/pykafka/rdkafka/simple_consumer.py", line 62, in __init__
    super(RdKafkaSimpleConsumer, self).__init__(**callargs)
  File "/usr/lib64/python2.7/site-packages/pykafka/simpleconsumer.py", line 216, in __init__
    self.start()
  File "/usr/lib64/python2.7/site-packages/pykafka/simpleconsumer.py", line 258, in start
    self._fetch_workers = self._setup_fetch_workers()
  File "/usr/lib64/python2.7/site-packages/pykafka/rdkafka/simple_consumer.py", line 75, in _setup_fetch_workers
    self._rdk_consumer.configure(conf=conf)
RdKafkaException: No such configuration property: "broker.version.fallback"
```

I'm not sure that it is right way to solve this issue but at least it works:
pykafka/rdkafka/simple_consumer.py
```python
  73         log.debug("Configuring _rdk_consumer...")
+ 74         conf = [c for c in conf if c[0] != 'broker.version.fallback']
  75         self._rdk_consumer.configure(conf=conf)
```

How to reproduce
================
0. Turn on `use_rdkafka`
1. Consume message using balancedconsumer

Eviron.
=====
 - librdkafka version (release number or git tag): 0.8.6
 - Apache Kafka version: 0.8.2.1
 - librdkafka client configuration: default(nothing custom configured)
 - Operating system: CentOS 7.2

**Comment by ummae** [comment]
opps i'm sorry I wrote wrong place :(

**Comment by edenhill** [comment]
You need librdkafka 0.9.1 or later for broker.version.fallback.
0.9.2 was just released so I suggest using that.
