### ISSUE TITLE
consumer crashed when multi consumer consume one partition,and commit callback

### ISSUE THREAD

**Issue by liuzibei2004** [edenhill/librdkafka#940]
Description
===========
I meet following crash:

```
(gdb) info threads   
  9 Thread 0x7f0f795aa700 (LWP 11656)  0x00007f0f87a1798e in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  8 Thread 0x7f0f8813b7a0 (LWP 11650)  0x00007f0f87a1798e in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  7 Thread 0x7f0f76184700 (LWP 11666)  0x00007f0f86daf0d3 in poll () from /lib64/libc.so.6
  6 Thread 0x7f0f76985700 (LWP 11665)  0x00007f0f86daf0d3 in poll () from /lib64/libc.so.6
  5 Thread 0x7f0f77186700 (LWP 11664)  0x00007f0f86daf0d3 in poll () from /lib64/libc.so.6
  4 Thread 0x7f0f77da7700 (LWP 11659)  0x00007f0f86daf0d3 in poll () from /lib64/libc.so.6
  3 Thread 0x7f0f785a8700 (LWP 11658)  0x00007f0f86daf0d3 in poll () from /lib64/libc.so.6
  2 Thread 0x7f0f78da9700 (LWP 11657)  0x00007f0f86daf0d3 in poll () from /lib64/libc.so.6
* 1 Thread 0x7f0f79dab700 (LWP 11655)  0x00007f0f86d02625 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f0f86d02625 in raise () from /lib64/libc.so.6
#1  0x00007f0f86d03e05 in abort () from /lib64/libc.so.6
#2  0x000000000068f47b in rd_kafka_crash (file=<value optimized out>, line=<value optimized out>, function=<value optimized out>, rk=0x0, reason=<value optimized out>) at rdkafka.c:2360
#3  0x00000000006a8607 in rd_kafka_offset_commit_cb_op (rk=0x15fbdb0, err=<value optimized out>, offsets=0x7f0f60000ae0) at rdkafka_offset.c:355
#4  0x00000000006bdcc7 in rd_kafka_cgrp_handle_OffsetCommit (rk=<value optimized out>, rkb=<value optimized out>, err=RD_KAFKA_RESP_ERR__NO_OFFSET, rkbuf=<value optimized out>, request=<value optimized out>, opaque=0x1b4a1550)
    at rdkafka_cgrp.c:840
#5  rd_kafka_cgrp_op_handle_OffsetCommit (rk=<value optimized out>, rkb=<value optimized out>, err=RD_KAFKA_RESP_ERR__NO_OFFSET, rkbuf=<value optimized out>, request=<value optimized out>, opaque=0x1b4a1550) at rdkafka_cgrp.c:880
#6  0x00000000006bf98d in rd_kafka_cgrp_op_serve (rkcg=0x15fc290) at rdkafka_cgrp.c:1517
#7  rd_kafka_cgrp_serve (rkcg=0x15fc290) at rdkafka_cgrp.c:1661
#8  0x0000000000693ad4 in rd_kafka_thread_main (arg=0x15fbdb0) at rdkafka.c:968
#9  0x00000000006c99ff in _thrd_wrapper_function (aArg=<value optimized out>) at tinycthread.c:611
#10 0x00007f0f87a139d1 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f0f86db88fd in clone () from /lib64/libc.so.6
```

How to reproduce
================
1,create one topic with on partition 
2,start two consumer,the two shared the same group id
3,period call commitAsync() in two consumer.
if I start one consumer only，everything ok.
when I start two，the two consumer will alternate crash.
I guess that when  the consumer who is not the partition's "owner" call "commitAsync()",it will creash.

Checklist
=========
Please provide the following information:

 - [ master branch] librdkafka version (release number or git tag):
 - [ kafka_2.11-0.9.0.1] Apache Kafka version:

**Comment by edenhill** [comment]
Which exact git sha are you on?

**Comment by liuzibei2004** [comment]
I'm so sorry.........
I download zip file from master on some day, and continue to use that version in these days.So I cann't give you the exact version.
When I tried the latest release version 0.9.2,everything ok now.....
I will remember to use the release version next time. T.T

**Comment by edenhill** [comment]
Great!
